<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 13 Chapter 13: bootnet package | Introduction to Network Analysis in igraph</title>
  <meta name="description" content="This is an instructional manual for PL4246 students. The output format is bookdown::gitbook." />
  <meta name="generator" content="bookdown 0.40 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 13 Chapter 13: bootnet package | Introduction to Network Analysis in igraph" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="This is an instructional manual for PL4246 students. The output format is bookdown::gitbook." />
  <meta name="github-repo" content="rstudio/bookdown-demo" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 13 Chapter 13: bootnet package | Introduction to Network Analysis in igraph" />
  
  <meta name="twitter:description" content="This is an instructional manual for PL4246 students. The output format is bookdown::gitbook." />
  

<meta name="author" content="Cynthia S. Q. Siew" />


<meta name="date" content="2024-10-14" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="ch12.html"/>
<link rel="next" href="ch14.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />
<link href="libs/bsTable-3.3.7/bootstrapTable.min.css" rel="stylesheet" />
<script src="libs/bsTable-3.3.7/bootstrapTable.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Introduction to Network Analysis</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Introduction to Network Analysis in <code>igraph</code></a>
<ul>
<li class="chapter" data-level="0.1" data-path="index.html"><a href="index.html#what-is-this-book-about"><i class="fa fa-check"></i><b>0.1</b> What is this book about?</a></li>
<li class="chapter" data-level="0.2" data-path="index.html"><a href="index.html#why-write-this-book"><i class="fa fa-check"></i><b>0.2</b> Why write this book?</a></li>
<li class="chapter" data-level="0.3" data-path="index.html"><a href="index.html#acknowledgements"><i class="fa fa-check"></i><b>0.3</b> Acknowledgements</a></li>
<li class="chapter" data-level="0.4" data-path="index.html"><a href="index.html#about-the-author"><i class="fa fa-check"></i><b>0.4</b> About the author</a></li>
<li class="chapter" data-level="0.5" data-path="index.html"><a href="index.html#table-of-contents"><i class="fa fa-check"></i><b>0.5</b> Table of Contents</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="ch1.html"><a href="ch1.html"><i class="fa fa-check"></i><b>1</b> Chapter 1: Installation and set up</a>
<ul>
<li class="chapter" data-level="1.1" data-path="ch1.html"><a href="ch1.html#installing-r-and-rstudio"><i class="fa fa-check"></i><b>1.1</b> Installing R and RStudio</a></li>
<li class="chapter" data-level="1.2" data-path="ch1.html"><a href="ch1.html#rstudio-cloud"><i class="fa fa-check"></i><b>1.2</b> RStudio Cloud</a></li>
<li class="chapter" data-level="1.3" data-path="ch1.html"><a href="ch1.html#installing-r-packages"><i class="fa fa-check"></i><b>1.3</b> Installing R packages</a>
<ul>
<li class="chapter" data-level="1.3.1" data-path="ch1.html"><a href="ch1.html#exercise"><i class="fa fa-check"></i><b>1.3.1</b> Exercise</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="ch2.html"><a href="ch2.html"><i class="fa fa-check"></i><b>2</b> Chapter 2: Programming and data science basics</a>
<ul>
<li class="chapter" data-level="2.1" data-path="ch2.html"><a href="ch2.html#the-rstudio-environment"><i class="fa fa-check"></i><b>2.1</b> The RStudio Environment</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="ch2.html"><a href="ch2.html#setting-up-a-project"><i class="fa fa-check"></i><b>2.1.1</b> Setting up a Project</a></li>
<li class="chapter" data-level="2.1.2" data-path="ch2.html"><a href="ch2.html#layout-of-rstudio"><i class="fa fa-check"></i><b>2.1.2</b> Layout of RStudio</a></li>
<li class="chapter" data-level="2.1.3" data-path="ch2.html"><a href="ch2.html#r-scripts-vs.-console"><i class="fa fa-check"></i><b>2.1.3</b> R scripts vs. Console</a></li>
<li class="chapter" data-level="2.1.4" data-path="ch2.html"><a href="ch2.html#working-with-r-scripts-is-recommended"><i class="fa fa-check"></i><b>2.1.4</b> Working with R scripts is recommended!</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="ch2.html"><a href="ch2.html#variables-and-data-types"><i class="fa fa-check"></i><b>2.2</b> Variables and Data Types</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="ch2.html"><a href="ch2.html#what-are-variables"><i class="fa fa-check"></i><b>2.2.1</b> What are variables?</a></li>
<li class="chapter" data-level="2.2.2" data-path="ch2.html"><a href="ch2.html#removing-objects"><i class="fa fa-check"></i><b>2.2.2</b> Removing objects</a></li>
<li class="chapter" data-level="2.2.3" data-path="ch2.html"><a href="ch2.html#saving-objects"><i class="fa fa-check"></i><b>2.2.3</b> Saving objects</a></li>
<li class="chapter" data-level="2.2.4" data-path="ch2.html"><a href="ch2.html#loading-objects"><i class="fa fa-check"></i><b>2.2.4</b> Loading objects</a></li>
<li class="chapter" data-level="2.2.5" data-path="ch2.html"><a href="ch2.html#what-are-vectors"><i class="fa fa-check"></i><b>2.2.5</b> What are vectors?</a></li>
<li class="chapter" data-level="2.2.6" data-path="ch2.html"><a href="ch2.html#cool-things-you-can-do-with-vectors"><i class="fa fa-check"></i><b>2.2.6</b> Cool things you can do with vectors</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="ch2.html"><a href="ch2.html#functions-and-arguments"><i class="fa fa-check"></i><b>2.3</b> Functions and Arguments</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="ch2.html"><a href="ch2.html#what-are-functions"><i class="fa fa-check"></i><b>2.3.1</b> What are functions?</a></li>
<li class="chapter" data-level="2.3.2" data-path="ch2.html"><a href="ch2.html#what-are-arguments"><i class="fa fa-check"></i><b>2.3.2</b> What are arguments?</a></li>
<li class="chapter" data-level="2.3.3" data-path="ch2.html"><a href="ch2.html#multiple-arguments"><i class="fa fa-check"></i><b>2.3.3</b> Multiple arguments</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="ch2.html"><a href="ch2.html#file-paths-and-working-directory"><i class="fa fa-check"></i><b>2.4</b> File Paths and Working Directory</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="ch2.html"><a href="ch2.html#navigation-in-computers"><i class="fa fa-check"></i><b>2.4.1</b> Navigation in computers</a></li>
<li class="chapter" data-level="2.4.2" data-path="ch2.html"><a href="ch2.html#helping-rstudio-find-your-stuff"><i class="fa fa-check"></i><b>2.4.2</b> Helping RStudio find your stuff</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="ch2.html"><a href="ch2.html#packages"><i class="fa fa-check"></i><b>2.5</b> Packages</a>
<ul>
<li class="chapter" data-level="2.5.1" data-path="ch2.html"><a href="ch2.html#what-are-packageslibraries"><i class="fa fa-check"></i><b>2.5.1</b> What are packages/libraries?</a></li>
<li class="chapter" data-level="2.5.2" data-path="ch2.html"><a href="ch2.html#installation-vs.-loading"><i class="fa fa-check"></i><b>2.5.2</b> Installation vs. Loading</a></li>
<li class="chapter" data-level="2.5.3" data-path="ch2.html"><a href="ch2.html#detaching-packages"><i class="fa fa-check"></i><b>2.5.3</b> Detaching packages</a></li>
</ul></li>
<li class="chapter" data-level="2.6" data-path="ch2.html"><a href="ch2.html#special-datatypes"><i class="fa fa-check"></i><b>2.6</b> Special Datatypes</a>
<ul>
<li class="chapter" data-level="2.6.1" data-path="ch2.html"><a href="ch2.html#dataframes"><i class="fa fa-check"></i><b>2.6.1</b> Dataframes</a></li>
<li class="chapter" data-level="2.6.2" data-path="ch2.html"><a href="ch2.html#loading-data-into-rstudio"><i class="fa fa-check"></i><b>2.6.2</b> Loading data into RStudio</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="ch3.html"><a href="ch3.html"><i class="fa fa-check"></i><b>3</b> Chapter 3: Introduction to network objects</a>
<ul>
<li class="chapter" data-level="3.1" data-path="ch3.html"><a href="ch3.html#what-is-a-network"><i class="fa fa-check"></i><b>3.1</b> What is a network?</a></li>
<li class="chapter" data-level="3.2" data-path="ch3.html"><a href="ch3.html#your-first-network"><i class="fa fa-check"></i><b>3.2</b> Your first network</a></li>
<li class="chapter" data-level="3.3" data-path="ch3.html"><a href="ch3.html#your-second-network"><i class="fa fa-check"></i><b>3.3</b> Your second network</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="ch3.html"><a href="ch3.html#exercise-1"><i class="fa fa-check"></i><b>3.3.1</b> Exercise</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="ch3.html"><a href="ch3.html#node-and-edge-attributes"><i class="fa fa-check"></i><b>3.4</b> Node and edge attributes</a>
<ul>
<li class="chapter" data-level="3.4.1" data-path="ch3.html"><a href="ch3.html#exercise-2"><i class="fa fa-check"></i><b>3.4.1</b> Exercise</a></li>
</ul></li>
<li class="chapter" data-level="3.5" data-path="ch3.html"><a href="ch3.html#graph-attributes"><i class="fa fa-check"></i><b>3.5</b> Graph attributes</a></li>
<li class="chapter" data-level="3.6" data-path="ch3.html"><a href="ch3.html#useful-functions-for-working-with-attributes"><i class="fa fa-check"></i><b>3.6</b> Useful functions for working with attributes</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="ch4.html"><a href="ch4.html"><i class="fa fa-check"></i><b>4</b> Chapter 4: From data to networks</a>
<ul>
<li class="chapter" data-level="4.1" data-path="ch4.html"><a href="ch4.html#how-are-networks-represented"><i class="fa fa-check"></i><b>4.1</b> How are networks represented?</a></li>
<li class="chapter" data-level="4.2" data-path="ch4.html"><a href="ch4.html#edge-list"><i class="fa fa-check"></i><b>4.2</b> Edge List</a></li>
<li class="chapter" data-level="4.3" data-path="ch4.html"><a href="ch4.html#adjacency-matrix"><i class="fa fa-check"></i><b>4.3</b> Adjacency Matrix</a></li>
<li class="chapter" data-level="4.4" data-path="ch4.html"><a href="ch4.html#importing-your-data-and-converting-into-a-network"><i class="fa fa-check"></i><b>4.4</b> Importing your data and converting into a network</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="ch4.html"><a href="ch4.html#importing-edge-lists"><i class="fa fa-check"></i><b>4.4.1</b> Importing edge lists</a></li>
<li class="chapter" data-level="4.4.2" data-path="ch4.html"><a href="ch4.html#importing-adjacency-matrices"><i class="fa fa-check"></i><b>4.4.2</b> Importing adjacency matrices</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="ch4.html"><a href="ch4.html#exercise-3"><i class="fa fa-check"></i><b>4.5</b> Exercise</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="ch5.html"><a href="ch5.html"><i class="fa fa-check"></i><b>5</b> Chapter 5: Manipulating network objects</a>
<ul>
<li class="chapter" data-level="5.1" data-path="ch5.html"><a href="ch5.html#set-up"><i class="fa fa-check"></i><b>5.1</b> Set up</a></li>
<li class="chapter" data-level="5.2" data-path="ch5.html"><a href="ch5.html#adding-node-attributes"><i class="fa fa-check"></i><b>5.2</b> Adding node attributes</a></li>
<li class="chapter" data-level="5.3" data-path="ch5.html"><a href="ch5.html#adding-edge-attributes"><i class="fa fa-check"></i><b>5.3</b> Adding edge attributes</a></li>
<li class="chapter" data-level="5.4" data-path="ch5.html"><a href="ch5.html#subsetting-the-network"><i class="fa fa-check"></i><b>5.4</b> Subsetting the network</a>
<ul>
<li class="chapter" data-level="5.4.1" data-path="ch5.html"><a href="ch5.html#subset-by-node-attributes"><i class="fa fa-check"></i><b>5.4.1</b> Subset by node attributes</a></li>
<li class="chapter" data-level="5.4.2" data-path="ch5.html"><a href="ch5.html#subset-by-a-target-node"><i class="fa fa-check"></i><b>5.4.2</b> Subset by a target node</a></li>
<li class="chapter" data-level="5.4.3" data-path="ch5.html"><a href="ch5.html#subset-by-edge-attributes"><i class="fa fa-check"></i><b>5.4.3</b> Subset by edge attributes</a></li>
<li class="chapter" data-level="5.4.4" data-path="ch5.html"><a href="ch5.html#subsetting-by-mutual-edges"><i class="fa fa-check"></i><b>5.4.4</b> Subsetting by mutual edges</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="ch5.html"><a href="ch5.html#useful-functions"><i class="fa fa-check"></i><b>5.5</b> Useful functions</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="ch6.html"><a href="ch6.html"><i class="fa fa-check"></i><b>6</b> Chapter 6: Macro-level network measures</a>
<ul>
<li class="chapter" data-level="6.1" data-path="ch6.html"><a href="ch6.html#average-degree"><i class="fa fa-check"></i><b>6.1</b> Average Degree</a></li>
<li class="chapter" data-level="6.2" data-path="ch6.html"><a href="ch6.html#average-shortest-path-length"><i class="fa fa-check"></i><b>6.2</b> Average Shortest Path Length</a></li>
<li class="chapter" data-level="6.3" data-path="ch6.html"><a href="ch6.html#global-clustering-coefficient"><i class="fa fa-check"></i><b>6.3</b> Global Clustering Coefficient</a></li>
<li class="chapter" data-level="6.4" data-path="ch6.html"><a href="ch6.html#small-world-index"><i class="fa fa-check"></i><b>6.4</b> Small World Index</a></li>
<li class="chapter" data-level="6.5" data-path="ch6.html"><a href="ch6.html#network-density"><i class="fa fa-check"></i><b>6.5</b> Network Density</a></li>
<li class="chapter" data-level="6.6" data-path="ch6.html"><a href="ch6.html#network-diameter"><i class="fa fa-check"></i><b>6.6</b> Network Diameter</a></li>
<li class="chapter" data-level="6.7" data-path="ch6.html"><a href="ch6.html#assortative-mixing"><i class="fa fa-check"></i><b>6.7</b> Assortative Mixing</a>
<ul>
<li class="chapter" data-level="6.7.1" data-path="ch6.html"><a href="ch6.html#assortative-mixing-by-degree-continuous-attributes"><i class="fa fa-check"></i><b>6.7.1</b> Assortative Mixing by Degree (continuous attributes)</a></li>
<li class="chapter" data-level="6.7.2" data-path="ch6.html"><a href="ch6.html#assortative-mixing-by-node-attributes-categorical-attributes"><i class="fa fa-check"></i><b>6.7.2</b> Assortative Mixing by Node Attributes (categorical attributes)</a></li>
</ul></li>
<li class="chapter" data-level="6.8" data-path="ch6.html"><a href="ch6.html#network-components"><i class="fa fa-check"></i><b>6.8</b> Network Components</a></li>
<li class="chapter" data-level="6.9" data-path="ch6.html"><a href="ch6.html#exercise-4"><i class="fa fa-check"></i><b>6.9</b> Exercise</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="ch7.html"><a href="ch7.html"><i class="fa fa-check"></i><b>7</b> Chapter 7: Micro-level network measures</a>
<ul>
<li class="chapter" data-level="7.1" data-path="ch7.html"><a href="ch7.html#degree"><i class="fa fa-check"></i><b>7.1</b> Degree</a>
<ul>
<li class="chapter" data-level="7.1.1" data-path="ch7.html"><a href="ch7.html#in--out--all-degree"><i class="fa fa-check"></i><b>7.1.1</b> In-, out-, all-degree</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="ch7.html"><a href="ch7.html#strength"><i class="fa fa-check"></i><b>7.2</b> Strength</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="ch7.html"><a href="ch7.html#in--out--all-strength"><i class="fa fa-check"></i><b>7.2.1</b> In-, out-, all-strength</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="ch7.html"><a href="ch7.html#local-clustering-coefficient"><i class="fa fa-check"></i><b>7.3</b> Local clustering coefficient</a>
<ul>
<li class="chapter" data-level="7.3.1" data-path="ch7.html"><a href="ch7.html#weighted-local-clustering-coefficient"><i class="fa fa-check"></i><b>7.3.1</b> Weighted local clustering coefficient</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="ch7.html"><a href="ch7.html#closeness-centrality"><i class="fa fa-check"></i><b>7.4</b> Closeness centrality</a>
<ul>
<li class="chapter" data-level="7.4.1" data-path="ch7.html"><a href="ch7.html#weighted-closeness-centrality"><i class="fa fa-check"></i><b>7.4.1</b> Weighted closeness centrality</a></li>
<li class="chapter" data-level="7.4.2" data-path="ch7.html"><a href="ch7.html#interpretation-of-edge-weights"><i class="fa fa-check"></i><b>7.4.2</b> Interpretation of edge weights</a></li>
<li class="chapter" data-level="7.4.3" data-path="ch7.html"><a href="ch7.html#directed-closeness-centrality"><i class="fa fa-check"></i><b>7.4.3</b> Directed closeness centrality</a></li>
</ul></li>
<li class="chapter" data-level="7.5" data-path="ch7.html"><a href="ch7.html#betweenness-centrality"><i class="fa fa-check"></i><b>7.5</b> Betweenness centrality</a>
<ul>
<li class="chapter" data-level="7.5.1" data-path="ch7.html"><a href="ch7.html#weighted-betweenness-centrality"><i class="fa fa-check"></i><b>7.5.1</b> Weighted betweenness centrality</a></li>
<li class="chapter" data-level="7.5.2" data-path="ch7.html"><a href="ch7.html#directed-betweenness-centrality"><i class="fa fa-check"></i><b>7.5.2</b> Directed betweenness centrality</a></li>
</ul></li>
<li class="chapter" data-level="7.6" data-path="ch7.html"><a href="ch7.html#page-rank-centrality"><i class="fa fa-check"></i><b>7.6</b> Page Rank centrality</a></li>
<li class="chapter" data-level="7.7" data-path="ch7.html"><a href="ch7.html#other-forms-of-node-centrality"><i class="fa fa-check"></i><b>7.7</b> Other forms of node centrality</a></li>
<li class="chapter" data-level="7.8" data-path="ch7.html"><a href="ch7.html#exporting-node-centrality-measures-for-data-analysis"><i class="fa fa-check"></i><b>7.8</b> Exporting node centrality measures for data analysis</a></li>
<li class="chapter" data-level="7.9" data-path="ch7.html"><a href="ch7.html#exercise-5"><i class="fa fa-check"></i><b>7.9</b> Exercise</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="ch8.html"><a href="ch8.html"><i class="fa fa-check"></i><b>8</b> Chapter 8: Meso-level network measures</a>
<ul>
<li class="chapter" data-level="8.1" data-path="ch8.html"><a href="ch8.html#how-do-network-scientists-find-communities-in-networks"><i class="fa fa-check"></i><b>8.1</b> How do network scientists “find” communities in networks?</a></li>
<li class="chapter" data-level="8.2" data-path="ch8.html"><a href="ch8.html#edge-betweenness-divisive-method"><i class="fa fa-check"></i><b>8.2</b> Edge betweenness (“divisive method”)</a></li>
<li class="chapter" data-level="8.3" data-path="ch8.html"><a href="ch8.html#louvain-method-greedy-maximization-method"><i class="fa fa-check"></i><b>8.3</b> Louvain method (“greedy, maximization method”)</a></li>
<li class="chapter" data-level="8.4" data-path="ch8.html"><a href="ch8.html#random-walker-dynamic-method"><i class="fa fa-check"></i><b>8.4</b> Random walker (“dynamic method”)</a></li>
<li class="chapter" data-level="8.5" data-path="ch8.html"><a href="ch8.html#infomap-information-theoretic-method"><i class="fa fa-check"></i><b>8.5</b> Infomap (“information-theoretic method”)</a></li>
<li class="chapter" data-level="8.6" data-path="ch8.html"><a href="ch8.html#comparison-of-methods"><i class="fa fa-check"></i><b>8.6</b> Comparison of methods</a>
<ul>
<li class="chapter" data-level="8.6.1" data-path="ch8.html"><a href="ch8.html#comparing-modularity"><i class="fa fa-check"></i><b>8.6.1</b> Comparing modularity</a></li>
<li class="chapter" data-level="8.6.2" data-path="ch8.html"><a href="ch8.html#comparing-community-membership"><i class="fa fa-check"></i><b>8.6.2</b> Comparing community membership</a></li>
</ul></li>
<li class="chapter" data-level="8.7" data-path="ch8.html"><a href="ch8.html#things-to-note"><i class="fa fa-check"></i><b>8.7</b> Things to note</a>
<ul>
<li class="chapter" data-level="8.7.1" data-path="ch8.html"><a href="ch8.html#weighted-and-directed-graphs"><i class="fa fa-check"></i><b>8.7.1</b> Weighted and directed graphs</a></li>
<li class="chapter" data-level="8.7.2" data-path="ch8.html"><a href="ch8.html#networks-with-multiple-components"><i class="fa fa-check"></i><b>8.7.2</b> Networks with multiple components</a></li>
<li class="chapter" data-level="8.7.3" data-path="ch8.html"><a href="ch8.html#calculating-modularity-for-self-defined-communities"><i class="fa fa-check"></i><b>8.7.3</b> Calculating modularity for self-defined communities</a></li>
<li class="chapter" data-level="8.7.4" data-path="ch8.html"><a href="ch8.html#comparing-different-runs"><i class="fa fa-check"></i><b>8.7.4</b> Comparing different runs</a></li>
<li class="chapter" data-level="8.7.5" data-path="ch8.html"><a href="ch8.html#other-community-detection-methods"><i class="fa fa-check"></i><b>8.7.5</b> Other community detection methods</a></li>
</ul></li>
<li class="chapter" data-level="8.8" data-path="ch8.html"><a href="ch8.html#exercise-6"><i class="fa fa-check"></i><b>8.8</b> Exercise</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="ch9.html"><a href="ch9.html"><i class="fa fa-check"></i><b>9</b> Chapter 9: Network models</a></li>
<li class="chapter" data-level="10" data-path="ch10.html"><a href="ch10.html"><i class="fa fa-check"></i><b>10</b> Chapter 10: Behaviors in the network</a></li>
<li class="chapter" data-level="11" data-path="ch11.html"><a href="ch11.html"><i class="fa fa-check"></i><b>11</b> Chapter 11: <code>keyplayer</code> package</a>
<ul>
<li class="chapter" data-level="11.1" data-path="ch11.html"><a href="ch11.html#set-up-1"><i class="fa fa-check"></i><b>11.1</b> Set up</a></li>
<li class="chapter" data-level="11.2" data-path="ch11.html"><a href="ch11.html#key-player-problem-negative"><i class="fa fa-check"></i><b>11.2</b> Key Player Problem-Negative</a></li>
<li class="chapter" data-level="11.3" data-path="ch11.html"><a href="ch11.html#key-player-problem-positive"><i class="fa fa-check"></i><b>11.3</b> Key Player Problem-Positive</a></li>
<li class="chapter" data-level="11.4" data-path="ch11.html"><a href="ch11.html#references"><i class="fa fa-check"></i><b>11.4</b> References</a></li>
<li class="chapter" data-level="11.5" data-path="ch11.html"><a href="ch11.html#exercise-7"><i class="fa fa-check"></i><b>11.5</b> Exercise</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="ch12.html"><a href="ch12.html"><i class="fa fa-check"></i><b>12</b> Chapter 12: <code>influenceR</code> package</a>
<ul>
<li class="chapter" data-level="12.1" data-path="ch12.html"><a href="ch12.html#set-up-2"><i class="fa fa-check"></i><b>12.1</b> Set up</a></li>
<li class="chapter" data-level="12.2" data-path="ch12.html"><a href="ch12.html#bridging-score"><i class="fa fa-check"></i><b>12.2</b> Bridging score</a>
<ul>
<li class="chapter" data-level="12.2.1" data-path="ch12.html"><a href="ch12.html#important-note-about-directed-graphs"><i class="fa fa-check"></i><b>12.2.1</b> Important note about directed graphs</a></li>
</ul></li>
<li class="chapter" data-level="12.3" data-path="ch12.html"><a href="ch12.html#effective-network-science"><i class="fa fa-check"></i><b>12.3</b> Effective network science</a>
<ul>
<li class="chapter" data-level="12.3.1" data-path="ch12.html"><a href="ch12.html#how-is-effective-network-science-different-from-local-clustering-coefficient"><i class="fa fa-check"></i><b>12.3.1</b> How is effective network science different from local clustering coefficient?</a></li>
<li class="chapter" data-level="12.3.2" data-path="ch12.html"><a href="ch12.html#important-note-about-directed-graphs-1"><i class="fa fa-check"></i><b>12.3.2</b> Important note about directed graphs</a></li>
</ul></li>
<li class="chapter" data-level="12.4" data-path="ch12.html"><a href="ch12.html#references-1"><i class="fa fa-check"></i><b>12.4</b> References</a></li>
<li class="chapter" data-level="12.5" data-path="ch12.html"><a href="ch12.html#exercise-8"><i class="fa fa-check"></i><b>12.5</b> Exercise</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="ch13.html"><a href="ch13.html"><i class="fa fa-check"></i><b>13</b> Chapter 13: <code>bootnet</code> package</a>
<ul>
<li class="chapter" data-level="13.1" data-path="ch13.html"><a href="ch13.html#chapter-outline"><i class="fa fa-check"></i><b>13.1</b> Chapter outline</a></li>
<li class="chapter" data-level="13.2" data-path="ch13.html"><a href="ch13.html#installation-of-bootnet"><i class="fa fa-check"></i><b>13.2</b> Installation of <code>bootnet</code></a>
<ul>
<li class="chapter" data-level="13.2.1" data-path="ch13.html"><a href="ch13.html#qgraph-vs.-igraph"><i class="fa fa-check"></i><b>13.2.1</b> <code>qgraph</code> vs. <code>igraph</code></a></li>
</ul></li>
<li class="chapter" data-level="13.3" data-path="ch13.html"><a href="ch13.html#dataset"><i class="fa fa-check"></i><b>13.3</b> Dataset</a></li>
<li class="chapter" data-level="13.4" data-path="ch13.html"><a href="ch13.html#estimate-a-partial-correlation-network"><i class="fa fa-check"></i><b>13.4</b> Estimate a partial correlation network</a>
<ul>
<li class="chapter" data-level="13.4.1" data-path="ch13.html"><a href="ch13.html#thresholding"><i class="fa fa-check"></i><b>13.4.1</b> Thresholding</a></li>
<li class="chapter" data-level="13.4.2" data-path="ch13.html"><a href="ch13.html#absolutizing"><i class="fa fa-check"></i><b>13.4.2</b> Absolutizing</a></li>
<li class="chapter" data-level="13.4.3" data-path="ch13.html"><a href="ch13.html#conversion-to-igraph"><i class="fa fa-check"></i><b>13.4.3</b> Conversion to igraph</a></li>
</ul></li>
<li class="chapter" data-level="13.5" data-path="ch13.html"><a href="ch13.html#sample-sizes"><i class="fa fa-check"></i><b>13.5</b> Sample sizes</a></li>
<li class="chapter" data-level="13.6" data-path="ch13.html"><a href="ch13.html#additional-resources"><i class="fa fa-check"></i><b>13.6</b> Additional resources</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="ch14.html"><a href="ch14.html"><i class="fa fa-check"></i><b>14</b> Chapter 14: Network visualization in <code>igraph</code></a>
<ul>
<li class="chapter" data-level="14.1" data-path="ch14.html"><a href="ch14.html#set-up-3"><i class="fa fa-check"></i><b>14.1</b> Set up</a></li>
<li class="chapter" data-level="14.2" data-path="ch14.html"><a href="ch14.html#visualizing-node-attributes"><i class="fa fa-check"></i><b>14.2</b> Visualizing node attributes</a>
<ul>
<li class="chapter" data-level="14.2.1" data-path="ch14.html"><a href="ch14.html#color-nodes-by-their-categorical-attributes"><i class="fa fa-check"></i><b>14.2.1</b> Color nodes by their categorical attributes</a></li>
<li class="chapter" data-level="14.2.2" data-path="ch14.html"><a href="ch14.html#color-nodes-by-their-continuous-attributes"><i class="fa fa-check"></i><b>14.2.2</b> Color nodes by their continuous attributes</a></li>
<li class="chapter" data-level="14.2.3" data-path="ch14.html"><a href="ch14.html#node-shapes-by-their-categorical-attributes"><i class="fa fa-check"></i><b>14.2.3</b> Node shapes by their categorical attributes</a></li>
<li class="chapter" data-level="14.2.4" data-path="ch14.html"><a href="ch14.html#node-size-by-their-continuous-attributes"><i class="fa fa-check"></i><b>14.2.4</b> Node size by their continuous attributes</a></li>
<li class="chapter" data-level="14.2.5" data-path="ch14.html"><a href="ch14.html#example-1-color-nodes-by-their-community-membership"><i class="fa fa-check"></i><b>14.2.5</b> Example 1: Color nodes by their community membership</a></li>
<li class="chapter" data-level="14.2.6" data-path="ch14.html"><a href="ch14.html#example-2-size-nodes-by-their-degree"><i class="fa fa-check"></i><b>14.2.6</b> Example 2: Size nodes by their degree</a></li>
</ul></li>
<li class="chapter" data-level="14.3" data-path="ch14.html"><a href="ch14.html#visualizing-edge-attributes"><i class="fa fa-check"></i><b>14.3</b> Visualizing edge attributes</a>
<ul>
<li class="chapter" data-level="14.3.1" data-path="ch14.html"><a href="ch14.html#color-edges-by-their-categorical-attributes"><i class="fa fa-check"></i><b>14.3.1</b> Color edges by their categorical attributes</a></li>
<li class="chapter" data-level="14.3.2" data-path="ch14.html"><a href="ch14.html#edge-thickness-based-on-their-continuous-attributes"><i class="fa fa-check"></i><b>14.3.2</b> Edge thickness based on their continuous attributes</a></li>
<li class="chapter" data-level="14.3.3" data-path="ch14.html"><a href="ch14.html#arrows-for-directed-edges"><i class="fa fa-check"></i><b>14.3.3</b> Arrows for directed edges</a></li>
</ul></li>
<li class="chapter" data-level="14.4" data-path="ch14.html"><a href="ch14.html#other"><i class="fa fa-check"></i><b>14.4</b> Other</a>
<ul>
<li class="chapter" data-level="14.4.1" data-path="ch14.html"><a href="ch14.html#graph-layouts"><i class="fa fa-check"></i><b>14.4.1</b> Graph layouts</a></li>
<li class="chapter" data-level="14.4.2" data-path="ch14.html"><a href="ch14.html#plot-title"><i class="fa fa-check"></i><b>14.4.2</b> Plot title</a></li>
<li class="chapter" data-level="14.4.3" data-path="ch14.html"><a href="ch14.html#add-a-subtitle"><i class="fa fa-check"></i><b>14.4.3</b> Add a subtitle</a></li>
<li class="chapter" data-level="14.4.4" data-path="ch14.html"><a href="ch14.html#multiple-plots"><i class="fa fa-check"></i><b>14.4.4</b> Multiple plots</a></li>
<li class="chapter" data-level="14.4.5" data-path="ch14.html"><a href="ch14.html#useful-links"><i class="fa fa-check"></i><b>14.4.5</b> Useful links</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="15" data-path="ch15.html"><a href="ch15.html"><i class="fa fa-check"></i><b>15</b> Chapter 15: Network visualization with other packages</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Introduction to Network Analysis in <code>igraph</code></a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="ch13" class="section level1 hasAnchor" number="13">
<h1><span class="header-section-number">Chapter 13</span> Chapter 13: <code>bootnet</code> package<a href="ch13.html#ch13" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>Psychometrics is the science of psychological measurement. It attempts to measure psychological constructs that are not usually directly observable. The core question in psychometrics is how to relate observable information (questionnaire responses, behaviors, test performance) to theoretical psychological constructs.</p>
<p>The underlying assumption is that the relationship between observables and psychological constructs is that of <em>common cause</em>. In other words, there is a hypothesized latent variable (representing the unobservable construct; e.g., intelligence) that causes or leads to the behaviors and responses that are observed (e.g., scores on Raven’s Progressive Matrices).</p>
<p>In recent years, a new area known as <strong>network psychometrics</strong> has developed and gained substantial attention among psychometricians. Instead of trying to uncover a latent variable from observable data, network psychometrics focuses on analyzing the patterns of covariances among observable data as a network representation. This enables researchers to leverage on the network science framework in order to quantify their structural properties.</p>
<p>For instance, Borsboom and Cramer (2013) argue that the complexity of psychopathology demands more sophisticated models that acknowledge its complexity. Traditional psychometric methods that assume a latent variable implicitly assume that clinical symptoms are caused by the disorder itself, but the evidence suggests that symptoms of mental disorders have reliable patterns of covariance that cannot be easily reduced to a single cause or latent variable. Instead of treating mental disorders as a “disease” that can be solved by finding the underlying cause(s) (i.e., the “disease” model in western medicine), psychometic network models view mental disorders as interactive systems of symptoms with reinforcing negative feedback loops and causal relationships.</p>
<div id="chapter-outline" class="section level2 hasAnchor" number="13.1">
<h2><span class="header-section-number">13.1</span> Chapter outline<a href="ch13.html#chapter-outline" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Throughout this book we have seen various examples of behavioral networks, and learned about the importance of clearly defining what the nodes and edges are representing. What are the nodes and edges of a psychometric network?</p>
<ul>
<li>Nodes: observed variables. In the example that we will work through, these would be the items on the survey that correspond to symptoms associated with post-traumatic stress disorder (PTSD).</li>
<li>Edges: strength of association between the observed variables. For instance, the strength of the correlation of two symptoms in the PTSD symptom list. This information has to be estimated from the data itself.</li>
</ul>
<p>In the rest of this chapter we will work through a concrete example to show you how to convert data from a survey to a network representation that you can analyze using the functions you’ve learned about earlier. Thereafter you should be able to apply the same steps to your own data to get the corresponding psychometric network.</p>
</div>
<div id="installation-of-bootnet" class="section level2 hasAnchor" number="13.2">
<h2><span class="header-section-number">13.2</span> Installation of <code>bootnet</code><a href="ch13.html#installation-of-bootnet" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>We need to first install the <code>bootnet</code> R library.</p>
<div class="sourceCode" id="cb364"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb364-1"><a href="ch13.html#cb364-1" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">&#39;bootnet&#39;</span>)</span></code></pre></div>
<div id="qgraph-vs.-igraph" class="section level3 hasAnchor" number="13.2.1">
<h3><span class="header-section-number">13.2.1</span> <code>qgraph</code> vs. <code>igraph</code><a href="ch13.html#qgraph-vs.-igraph" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>It is important to keep in mind that that network objects created by the <code>bootnet</code> R package are <em>not</em> <code>igraph</code> objects; instead, they are <code>qgraph</code> objects, a different class of data objects specially created for <code>bootnet</code> and other packages for psychometric network analysis. In order for you to use the code provided in this book, we will need to first extract the adjacency matrix representation of this object and convert it to an <code>igraph</code> network object. I will show you how to do this later in the chapter.</p>
</div>
</div>
<div id="dataset" class="section level2 hasAnchor" number="13.3">
<h2><span class="header-section-number">13.3</span> Dataset<a href="ch13.html#dataset" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The dataset that we will use in this chapter comes from 359 women who were enrolled in a community substance program and met the criteria for either PTSD or sub-threshold PTSD, based on the DSM-IV. This data was obtained from Hien et al. (2009) and adapted slightly for teaching purposes.</p>
<p>They completed the PTSD Symptom Scale-Self Report (PSS-SR; Foa et al., 1993) by rating the frequency at which they experienced each of symptoms on the following scale: 1 (not at all), 2 (once a week), 3 (2 - 4 times a week), 4 (5 or more times a week).</p>
<p>Foa, E. B., Riggs, D. S., Dancu, C. V., &amp; Rothbaum, B. O. (1993). Reliability and validity of a brief instrument for assessing post‐traumatic stress disorder. Journal of Traumatic Stress, 6(4), 459-473.</p>
<p>Hien DA, Wells EA, Jiang H, Suarez-Morales L, Campbell AN, Cohen LR, Zhang Y, et al. Multisite randomized trial of behavioral interventions for women with co-occurring ptsd and substance use disorders. Journal of Consulting and Clinical Psychology. 2009;77(4):607–619. doi: 10.1037/a0016227</p>
<p>As we can see below, there are 17 items in the PSS-SR, corresponding to the columns of the data frame, and 359 responses corresponding to the rows of the data frame. The responses are ordinal and range from 1 to 5.</p>
<div class="sourceCode" id="cb365"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb365-1"><a href="ch13.html#cb365-1" tabindex="-1"></a><span class="fu">load</span>(<span class="st">&#39;data/ptsd_freq.RData&#39;</span>) <span class="co"># load pre-processed data </span></span>
<span id="cb365-2"><a href="ch13.html#cb365-2" tabindex="-1"></a></span>
<span id="cb365-3"><a href="ch13.html#cb365-3" tabindex="-1"></a>qs_freq_wide[<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>,<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>] <span class="co"># each row = 1 subject, each column = 1 item </span></span></code></pre></div>
<pre><code>## # A tibble: 3 × 5
##   `AVOID REMINDERS OF THE TRAUMA` `BAD DREAMS ABOUT THE TRAUMA` `BEING JUMPY OR EASILY STARTLED` `BEING OVER ALERT` `DISTANT OR CUT OFF FROM PEOPLE`
##                             &lt;dbl&gt;                         &lt;dbl&gt;                            &lt;dbl&gt;              &lt;dbl&gt;                            &lt;dbl&gt;
## 1                               4                             1                                4                  4                                1
## 2                               1                             3                                2                  3                                1
## 3                               4                             2                                1                  2                                2</code></pre>
<div class="sourceCode" id="cb367"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb367-1"><a href="ch13.html#cb367-1" tabindex="-1"></a><span class="fu">colnames</span>(qs_freq_wide) <span class="co"># list of items </span></span></code></pre></div>
<pre><code>##  [1] &quot;AVOID REMINDERS OF THE TRAUMA&quot;  &quot;BAD DREAMS ABOUT THE TRAUMA&quot;    &quot;BEING JUMPY OR EASILY STARTLED&quot; &quot;BEING OVER ALERT&quot;               &quot;DISTANT OR CUT OFF FROM PEOPLE&quot; &quot;FEELING EMOTIONALLY NUMB&quot;      
##  [7] &quot;FEELING IRRITABLE&quot;              &quot;FEELING PLANS WONT COME TRUE&quot;   &quot;HAVING TROUBLE CONCENTRATING&quot;   &quot;HAVING TROUBLE SLEEPING&quot;        &quot;LESS INTEREST IN ACTIVITIES&quot;    &quot;NOT ABLE TO REMEMBER&quot;          
## [13] &quot;NOT THINKING ABOUT TRAUMA&quot;      &quot;PHYSICAL REACTIONS&quot;             &quot;RELIVING THE TRAUMA&quot;            &quot;UPSET WHEN REMINDED OF TRAUMA&quot;  &quot;UPSETTING THOUGHTS OR IMAGES&quot;</code></pre>
</div>
<div id="estimate-a-partial-correlation-network" class="section level2 hasAnchor" number="13.4">
<h2><span class="header-section-number">13.4</span> Estimate a partial correlation network<a href="ch13.html#estimate-a-partial-correlation-network" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>To represent the associations across the 17 items in our dataset, we will estimate a <em>partial correlation</em> network. The partial correlation depicts the strength of association of 2 variables after conditioning on other variables.</p>
<p>We make use of the <code>estimateNetwork</code> function from bootnet to help us do this. To estimate a partial correlation network, we need to specify an additional argument, <code>default = "pcor"</code>.</p>
<div class="sourceCode" id="cb369"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb369-1"><a href="ch13.html#cb369-1" tabindex="-1"></a><span class="fu">library</span>(bootnet)</span></code></pre></div>
<pre><code>## This is bootnet 1.6</code></pre>
<pre><code>## For questions and issues, please see github.com/SachaEpskamp/bootnet.</code></pre>
<div class="sourceCode" id="cb372"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb372-1"><a href="ch13.html#cb372-1" tabindex="-1"></a>ptsd_network <span class="ot">&lt;-</span> <span class="fu">estimateNetwork</span>(qs_freq_wide, <span class="at">default =</span> <span class="st">&quot;pcor&quot;</span>) </span></code></pre></div>
<pre><code>## Estimating Network. Using package::function:
##   - qgraph::qgraph(..., graph = &#39;pcor&#39;) for network computation
##   - psych::corr.p for significance thresholding</code></pre>
<div class="sourceCode" id="cb374"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb374-1"><a href="ch13.html#cb374-1" tabindex="-1"></a><span class="co"># pcor = partial correlation network</span></span>
<span id="cb374-2"><a href="ch13.html#cb374-2" tabindex="-1"></a></span>
<span id="cb374-3"><a href="ch13.html#cb374-3" tabindex="-1"></a><span class="fu">summary</span>(ptsd_network) <span class="co"># how many nodes and edges does this network have?</span></span></code></pre></div>
<pre><code>## 
## === Estimated network ===
## Number of nodes: 17 
## Number of non-zero edges: 136 / 136 
## Mean weight: 0.05363509 
## Network stored in object$graph 
##  
## Default set used: pcor 
##  
## Use plot(object) to plot estimated network 
## Use bootnet(object) to bootstrap edge weights and centrality indices 
## 
## Relevant references:
## 
##      Epskamp, S., Borsboom, D., &amp; Fried, E. I. (2016). Estimating psychological networks and their accuracy: a tutorial paper. arXiv preprint, arXiv:1604.08462.</code></pre>
<p>First, notice, that the <code>summary</code> function gives us a very different output than what we are used to. This is because <code>ptsd_network</code> is a <code>qgraph</code> object, not an <code>igraph</code> object. That said, the output is quite straightforward and you should be able to tell that there are 17 nodes and 136/136 non-zero edges.</p>
<p>Before proceeding, note that there are several different methods to estimate a network from psychometric data (type in <code>?estimateNetwork</code> into the console to see all of the different estimator methods that <code>bootnet</code> can use). For demonstration purposes, I have shown you just one of those approaches (i.e., partial correlation). In practice, which method you decide on depends on the properties of your data (i.e, is it categorical, continuous, normally distributed?) and how conservative you want your model to be. See “Additional resources”.</p>
<div id="thresholding" class="section level3 hasAnchor" number="13.4.1">
<h3><span class="header-section-number">13.4.1</span> Thresholding<a href="ch13.html#thresholding" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p><code>ptsd_network</code> contains 17 nodes and 136/136 non-zero edges. Notice that the number 136 corresponds to the maximum number of edges possible in a network of 17 nodes (test this for your yourself by calculating the number of possible combinations of 2 from 17 options). The presence of 136 non-zero edges indicates that this is in fact a fully connected graph.</p>
<p>A fully connected network is a rather meaningless representation to work with as there will be little to no variance in the node-level measures. Because many of these correlations depict very weak relationships, we can remove such non-significant correlations by including the argument <code>threshold = 'sig'</code>.</p>
<div class="sourceCode" id="cb376"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb376-1"><a href="ch13.html#cb376-1" tabindex="-1"></a>ptsd_network <span class="ot">&lt;-</span> <span class="fu">estimateNetwork</span>(qs_freq_wide, <span class="at">default =</span> <span class="st">&quot;pcor&quot;</span>, </span>
<span id="cb376-2"><a href="ch13.html#cb376-2" tabindex="-1"></a>                                <span class="at">threshold =</span> <span class="st">&#39;sig&#39;</span>) </span></code></pre></div>
<pre><code>## Estimating Network. Using package::function:
##   - qgraph::qgraph(..., graph = &#39;pcor&#39;) for network computation
##   - psych::corr.p for significance thresholding</code></pre>
<div class="sourceCode" id="cb378"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb378-1"><a href="ch13.html#cb378-1" tabindex="-1"></a><span class="co"># pcor = partial correlation network, only retain significant edges </span></span>
<span id="cb378-2"><a href="ch13.html#cb378-2" tabindex="-1"></a></span>
<span id="cb378-3"><a href="ch13.html#cb378-3" tabindex="-1"></a><span class="fu">summary</span>(ptsd_network) <span class="co"># how many nodes and edges does this network have?</span></span></code></pre></div>
<pre><code>## 
## === Estimated network ===
## Number of nodes: 17 
## Number of non-zero edges: 31 / 136 
## Mean weight: 0.03630966 
## Network stored in object$graph 
##  
## Default set used: pcor 
##  
## Use plot(object) to plot estimated network 
## Use bootnet(object) to bootstrap edge weights and centrality indices 
## 
## Relevant references:
## 
##      Epskamp, S., Borsboom, D., &amp; Fried, E. I. (2016). Estimating psychological networks and their accuracy: a tutorial paper. arXiv preprint, arXiv:1604.08462.</code></pre>
<p>After including statistical significance as a threshold to remove edges depicting weak correlations, <code>ptsd_network</code> contains 17 nodes and 31 edges.</p>
</div>
<div id="absolutizing" class="section level3 hasAnchor" number="13.4.2">
<h3><span class="header-section-number">13.4.2</span> Absolutizing<a href="ch13.html#absolutizing" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>We can view the adjacency matrix of the network from running the following:</p>
<div class="sourceCode" id="cb380"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb380-1"><a href="ch13.html#cb380-1" tabindex="-1"></a>ptsd_network<span class="sc">$</span>graph</span></code></pre></div>
<pre><code>##            AROTT      BDATT      BJOES       BOA    DOCOFP       FEN       FEI     FPWCT        HTC       HTS      LIIA      NATR      NTAT       PHR       RTT      UWROT      UTOI
## AROTT  0.0000000  0.0000000  0.0000000 0.1555554 0.0000000 0.0000000 0.0000000 0.0000000  0.0000000 0.0000000 0.0000000 0.0000000 0.1515577 0.1746399 0.0000000  0.0000000 0.0000000
## BDATT  0.0000000  0.0000000  0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 -0.1221041 0.0000000 0.0000000 0.0000000 0.0000000 0.1089284 0.0000000  0.1461690 0.1710409
## BJOES  0.0000000  0.0000000  0.0000000 0.4075190 0.0000000 0.0000000 0.0000000 0.0000000  0.0000000 0.0000000 0.1129132 0.0000000 0.1204094 0.1692879 0.0000000 -0.1109757 0.0000000
## BOA    0.1555554  0.0000000  0.4075190 0.0000000 0.0000000 0.1423142 0.0000000 0.0000000  0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000  0.0000000 0.0000000
## DOCOFP 0.0000000  0.0000000  0.0000000 0.0000000 0.0000000 0.2357181 0.1334469 0.0000000  0.0000000 0.0000000 0.3509726 0.0000000 0.0000000 0.0000000 0.0000000  0.0000000 0.0000000
## FEN    0.0000000  0.0000000  0.0000000 0.1423142 0.2357181 0.0000000 0.1410481 0.1474119  0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000  0.0000000 0.0000000
## FEI    0.0000000  0.0000000  0.0000000 0.0000000 0.1334469 0.1410481 0.0000000 0.1214582  0.1793871 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000  0.0000000 0.0000000
## FPWCT  0.0000000  0.0000000  0.0000000 0.0000000 0.0000000 0.1474119 0.1214582 0.0000000  0.0000000 0.0000000 0.2044012 0.0000000 0.0000000 0.0000000 0.0000000  0.0000000 0.0000000
## HTC    0.0000000 -0.1221041  0.0000000 0.0000000 0.0000000 0.0000000 0.1793871 0.0000000  0.0000000 0.1332300 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000  0.0000000 0.0000000
## HTS    0.0000000  0.0000000  0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000  0.1332300 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000  0.0000000 0.1351728
## LIIA   0.0000000  0.0000000  0.1129132 0.0000000 0.3509726 0.0000000 0.0000000 0.2044012  0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.1093724  0.0000000 0.0000000
## NATR   0.0000000  0.0000000  0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000  0.0000000 0.0000000 0.0000000 0.0000000 0.1711055 0.0000000 0.1487162  0.1546641 0.0000000
## NTAT   0.1515577  0.0000000  0.1204094 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000  0.0000000 0.0000000 0.0000000 0.1711055 0.0000000 0.0000000 0.0000000  0.1169038 0.0000000
## PHR    0.1746399  0.1089284  0.1692879 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000  0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.1811024  0.0000000 0.0000000
## RTT    0.0000000  0.0000000  0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000  0.0000000 0.0000000 0.1093724 0.1487162 0.0000000 0.1811024 0.0000000  0.0000000 0.1970405
## UWROT  0.0000000  0.1461690 -0.1109757 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000  0.0000000 0.0000000 0.0000000 0.1546641 0.1169038 0.0000000 0.0000000  0.0000000 0.4497070
## UTOI   0.0000000  0.1710409  0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000  0.0000000 0.1351728 0.0000000 0.0000000 0.0000000 0.0000000 0.1970405  0.4497070 0.0000000</code></pre>
<p>You may notice from the adjacency matrix that some partial correlations are negative. For instance, the correlation between HTC and BDATT is -0.1221041. However, when edge weights are negative, certain network measures cannot be computed and so we need to convert them to a positive value (but maintain the magnitude of the effect). Edges that depict a “positive” or “negative” meaning are associated with the theory of <a href="https://en.wikipedia.org/wiki/Signed_network">signed networks</a>, which are beyond the scope of this book. Interested readers can refer to the <a href="https://www.r-bloggers.com/2020/01/a-package-for-analysing-signed-networks/"><code>signnet</code> R package</a> for further information about how to analyze signed networks.</p>
<p>The code below shows you how to absolutize the matrix and assigns the output as a new data object <code>my_adj_mat</code>.</p>
<div class="sourceCode" id="cb382"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb382-1"><a href="ch13.html#cb382-1" tabindex="-1"></a><span class="co"># make all edge weights positive </span></span>
<span id="cb382-2"><a href="ch13.html#cb382-2" tabindex="-1"></a>my_adj_mat <span class="ot">&lt;-</span> <span class="fu">abs</span>(ptsd_network<span class="sc">$</span>graph)</span>
<span id="cb382-3"><a href="ch13.html#cb382-3" tabindex="-1"></a></span>
<span id="cb382-4"><a href="ch13.html#cb382-4" tabindex="-1"></a>my_adj_mat[<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>,<span class="dv">1</span><span class="sc">:</span><span class="dv">7</span>]</span></code></pre></div>
<pre><code>##            AROTT     BDATT    BJOES       BOA    DOCOFP       FEN       FEI
## AROTT  0.0000000 0.0000000 0.000000 0.1555554 0.0000000 0.0000000 0.0000000
## BDATT  0.0000000 0.0000000 0.000000 0.0000000 0.0000000 0.0000000 0.0000000
## BJOES  0.0000000 0.0000000 0.000000 0.4075190 0.0000000 0.0000000 0.0000000
## BOA    0.1555554 0.0000000 0.407519 0.0000000 0.0000000 0.1423142 0.0000000
## DOCOFP 0.0000000 0.0000000 0.000000 0.0000000 0.0000000 0.2357181 0.1334469
## FEN    0.0000000 0.0000000 0.000000 0.1423142 0.2357181 0.0000000 0.1410481
## FEI    0.0000000 0.0000000 0.000000 0.0000000 0.1334469 0.1410481 0.0000000
## FPWCT  0.0000000 0.0000000 0.000000 0.0000000 0.0000000 0.1474119 0.1214582
## HTC    0.0000000 0.1221041 0.000000 0.0000000 0.0000000 0.0000000 0.1793871
## HTS    0.0000000 0.0000000 0.000000 0.0000000 0.0000000 0.0000000 0.0000000</code></pre>
</div>
<div id="conversion-to-igraph" class="section level3 hasAnchor" number="13.4.3">
<h3><span class="header-section-number">13.4.3</span> Conversion to igraph<a href="ch13.html#conversion-to-igraph" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>In the final step, we need to convert the matrix object into an <code>igraph</code> network, using a function that should be familiar to you by now! (see Chapter 2/3).</p>
<div class="sourceCode" id="cb384"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb384-1"><a href="ch13.html#cb384-1" tabindex="-1"></a><span class="fu">library</span>(igraph) <span class="co"># load the package</span></span>
<span id="cb384-2"><a href="ch13.html#cb384-2" tabindex="-1"></a></span>
<span id="cb384-3"><a href="ch13.html#cb384-3" tabindex="-1"></a><span class="co"># why we should use this particular function? </span></span>
<span id="cb384-4"><a href="ch13.html#cb384-4" tabindex="-1"></a>ptsd_network_igraph <span class="ot">&lt;-</span> <span class="fu">graph_from_adjacency_matrix</span>(my_adj_mat, </span>
<span id="cb384-5"><a href="ch13.html#cb384-5" tabindex="-1"></a>                                                   <span class="at">mode =</span> <span class="st">&#39;undirected&#39;</span>, </span>
<span id="cb384-6"><a href="ch13.html#cb384-6" tabindex="-1"></a>                                                   <span class="at">weighted =</span> <span class="cn">TRUE</span>)</span>
<span id="cb384-7"><a href="ch13.html#cb384-7" tabindex="-1"></a></span>
<span id="cb384-8"><a href="ch13.html#cb384-8" tabindex="-1"></a><span class="fu">summary</span>(ptsd_network_igraph)</span></code></pre></div>
<pre><code>## IGRAPH c01d619 UNW- 17 31 -- 
## + attr: name (v/c), weight (e/n)</code></pre>
<p>We can easily see that the network contains 17 nodes and 31 edges, and is an undirected and weighted graph. The weights correspond to the strength of the partial correlation between those two items, and only significant correlations were retained as edges. The edges are undirected because direction of causality cannot be inferred from the correlations.</p>
<p>Thereafter, we can easily compute various network measures for the network.</p>
<div class="sourceCode" id="cb386"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb386-1"><a href="ch13.html#cb386-1" tabindex="-1"></a><span class="co"># degree of nodes</span></span>
<span id="cb386-2"><a href="ch13.html#cb386-2" tabindex="-1"></a><span class="fu">degree</span>(ptsd_network_igraph)</span></code></pre></div>
<pre><code>##  AROTT  BDATT  BJOES    BOA DOCOFP    FEN    FEI  FPWCT    HTC    HTS   LIIA   NATR   NTAT    PHR    RTT  UWROT   UTOI 
##      3      4      5      3      3      4      4      3      3      2      4      3      4      4      4      5      4</code></pre>
<div class="sourceCode" id="cb388"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb388-1"><a href="ch13.html#cb388-1" tabindex="-1"></a><span class="co"># global clustering coefficient </span></span>
<span id="cb388-2"><a href="ch13.html#cb388-2" tabindex="-1"></a><span class="fu">transitivity</span>(ptsd_network_igraph, <span class="at">type =</span> <span class="st">&#39;global&#39;</span>)</span></code></pre></div>
<pre><code>## [1] 0.1724138</code></pre>
<p><img src="bookdown-demo_files/figure-html/test-1.png" width="672" /></p>
</div>
</div>
<div id="sample-sizes" class="section level2 hasAnchor" number="13.5">
<h2><span class="header-section-number">13.5</span> Sample sizes<a href="ch13.html#sample-sizes" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>A common pitfall when trying to use <code>bootnet</code> to estimate a network occurs when sample sizes are simply too small in order to robustly estimate the covariance structure (<code>bootnet</code> throws an error or returns a network with 0 edges). In such cases, the best solution is to collect more data or find larger datasets. If one insists on sticking with the low-quality dataset, it is always possible to estimate a correlation matrix through other packages and conduct your own thresholding, since it is non-trivial to convert any numeric (adjacency) matrix into a network. But this is not recommended practice.</p>
</div>
<div id="additional-resources" class="section level2 hasAnchor" number="13.6">
<h2><span class="header-section-number">13.6</span> Additional resources<a href="ch13.html#additional-resources" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Epskamp, S., Borsboom, D., &amp; Fried, E. I. (2018). Estimating psychological networks and their accuracy: A tutorial paper. Behavior Research Methods, 50(1), 195-212.</p>
<p>Snijders, T. A., &amp; Borgatti, S. P. (1999). Non-parametric standard errors and tests for network statistics. Connections, 22(2), 161-170.</p>
<p>Isvoranu, A.-M., Epskamp, S., Waldorp, L., &amp; Borsboom, D. (Eds.). (2022). Network Psychometrics with R: A Guide for Behavioral and Social Scientists (1st ed.). Routledge. <a href="https://doi.org/10.4324/9781003111238" class="uri">https://doi.org/10.4324/9781003111238</a></p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="ch12.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="ch14.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/csqsiew/intro-to-igraph13-bootnet.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
