<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 6 Chapter 6: Macro-level network measures | Introduction to Network Analysis in igraph</title>
  <meta name="description" content="This is an instructional manual for PL4246 students. The output format is bookdown::gitbook." />
  <meta name="generator" content="bookdown 0.40 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 6 Chapter 6: Macro-level network measures | Introduction to Network Analysis in igraph" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="This is an instructional manual for PL4246 students. The output format is bookdown::gitbook." />
  <meta name="github-repo" content="rstudio/bookdown-demo" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 6 Chapter 6: Macro-level network measures | Introduction to Network Analysis in igraph" />
  
  <meta name="twitter:description" content="This is an instructional manual for PL4246 students. The output format is bookdown::gitbook." />
  

<meta name="author" content="Cynthia S. Q. Siew" />


<meta name="date" content="2024-11-07" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="ch5.html"/>
<link rel="next" href="ch7.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />
<link href="libs/bsTable-3.3.7/bootstrapTable.min.css" rel="stylesheet" />
<script src="libs/bsTable-3.3.7/bootstrapTable.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Introduction to Network Analysis</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Introduction to Network Analysis in <code>igraph</code></a>
<ul>
<li class="chapter" data-level="0.1" data-path="index.html"><a href="index.html#what-is-this-book-about"><i class="fa fa-check"></i><b>0.1</b> What is this book about?</a></li>
<li class="chapter" data-level="0.2" data-path="index.html"><a href="index.html#why-write-this-book"><i class="fa fa-check"></i><b>0.2</b> Why write this book?</a></li>
<li class="chapter" data-level="0.3" data-path="index.html"><a href="index.html#acknowledgements"><i class="fa fa-check"></i><b>0.3</b> Acknowledgements</a></li>
<li class="chapter" data-level="0.4" data-path="index.html"><a href="index.html#about-the-author"><i class="fa fa-check"></i><b>0.4</b> About the author</a></li>
<li class="chapter" data-level="0.5" data-path="index.html"><a href="index.html#table-of-contents"><i class="fa fa-check"></i><b>0.5</b> Table of Contents</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="ch1.html"><a href="ch1.html"><i class="fa fa-check"></i><b>1</b> Chapter 1: Installation and set up</a>
<ul>
<li class="chapter" data-level="1.1" data-path="ch1.html"><a href="ch1.html#installing-r-and-rstudio"><i class="fa fa-check"></i><b>1.1</b> Installing R and RStudio</a></li>
<li class="chapter" data-level="1.2" data-path="ch1.html"><a href="ch1.html#rstudio-cloud"><i class="fa fa-check"></i><b>1.2</b> RStudio Cloud</a></li>
<li class="chapter" data-level="1.3" data-path="ch1.html"><a href="ch1.html#installing-r-packages"><i class="fa fa-check"></i><b>1.3</b> Installing R packages</a>
<ul>
<li class="chapter" data-level="1.3.1" data-path="ch1.html"><a href="ch1.html#exercise"><i class="fa fa-check"></i><b>1.3.1</b> Exercise</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="ch2.html"><a href="ch2.html"><i class="fa fa-check"></i><b>2</b> Chapter 2: Programming and data science basics</a>
<ul>
<li class="chapter" data-level="2.1" data-path="ch2.html"><a href="ch2.html#the-rstudio-environment"><i class="fa fa-check"></i><b>2.1</b> The RStudio Environment</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="ch2.html"><a href="ch2.html#setting-up-a-project"><i class="fa fa-check"></i><b>2.1.1</b> Setting up a Project</a></li>
<li class="chapter" data-level="2.1.2" data-path="ch2.html"><a href="ch2.html#layout-of-rstudio"><i class="fa fa-check"></i><b>2.1.2</b> Layout of RStudio</a></li>
<li class="chapter" data-level="2.1.3" data-path="ch2.html"><a href="ch2.html#r-scripts-vs.-console"><i class="fa fa-check"></i><b>2.1.3</b> R scripts vs. Console</a></li>
<li class="chapter" data-level="2.1.4" data-path="ch2.html"><a href="ch2.html#working-with-r-scripts-is-recommended"><i class="fa fa-check"></i><b>2.1.4</b> Working with R scripts is recommended!</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="ch2.html"><a href="ch2.html#variables-and-data-types"><i class="fa fa-check"></i><b>2.2</b> Variables and Data Types</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="ch2.html"><a href="ch2.html#what-are-variables"><i class="fa fa-check"></i><b>2.2.1</b> What are variables?</a></li>
<li class="chapter" data-level="2.2.2" data-path="ch2.html"><a href="ch2.html#removing-objects"><i class="fa fa-check"></i><b>2.2.2</b> Removing objects</a></li>
<li class="chapter" data-level="2.2.3" data-path="ch2.html"><a href="ch2.html#saving-objects"><i class="fa fa-check"></i><b>2.2.3</b> Saving objects</a></li>
<li class="chapter" data-level="2.2.4" data-path="ch2.html"><a href="ch2.html#loading-objects"><i class="fa fa-check"></i><b>2.2.4</b> Loading objects</a></li>
<li class="chapter" data-level="2.2.5" data-path="ch2.html"><a href="ch2.html#what-are-vectors"><i class="fa fa-check"></i><b>2.2.5</b> What are vectors?</a></li>
<li class="chapter" data-level="2.2.6" data-path="ch2.html"><a href="ch2.html#cool-things-you-can-do-with-vectors"><i class="fa fa-check"></i><b>2.2.6</b> Cool things you can do with vectors</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="ch2.html"><a href="ch2.html#functions-and-arguments"><i class="fa fa-check"></i><b>2.3</b> Functions and Arguments</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="ch2.html"><a href="ch2.html#what-are-functions"><i class="fa fa-check"></i><b>2.3.1</b> What are functions?</a></li>
<li class="chapter" data-level="2.3.2" data-path="ch2.html"><a href="ch2.html#what-are-arguments"><i class="fa fa-check"></i><b>2.3.2</b> What are arguments?</a></li>
<li class="chapter" data-level="2.3.3" data-path="ch2.html"><a href="ch2.html#multiple-arguments"><i class="fa fa-check"></i><b>2.3.3</b> Multiple arguments</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="ch2.html"><a href="ch2.html#file-paths-and-working-directory"><i class="fa fa-check"></i><b>2.4</b> File Paths and Working Directory</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="ch2.html"><a href="ch2.html#navigation-in-computers"><i class="fa fa-check"></i><b>2.4.1</b> Navigation in computers</a></li>
<li class="chapter" data-level="2.4.2" data-path="ch2.html"><a href="ch2.html#helping-rstudio-find-your-stuff"><i class="fa fa-check"></i><b>2.4.2</b> Helping RStudio find your stuff</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="ch2.html"><a href="ch2.html#packages"><i class="fa fa-check"></i><b>2.5</b> Packages</a>
<ul>
<li class="chapter" data-level="2.5.1" data-path="ch2.html"><a href="ch2.html#what-are-packageslibraries"><i class="fa fa-check"></i><b>2.5.1</b> What are packages/libraries?</a></li>
<li class="chapter" data-level="2.5.2" data-path="ch2.html"><a href="ch2.html#installation-vs.-loading"><i class="fa fa-check"></i><b>2.5.2</b> Installation vs. Loading</a></li>
<li class="chapter" data-level="2.5.3" data-path="ch2.html"><a href="ch2.html#detaching-packages"><i class="fa fa-check"></i><b>2.5.3</b> Detaching packages</a></li>
</ul></li>
<li class="chapter" data-level="2.6" data-path="ch2.html"><a href="ch2.html#special-datatypes"><i class="fa fa-check"></i><b>2.6</b> Special Datatypes</a>
<ul>
<li class="chapter" data-level="2.6.1" data-path="ch2.html"><a href="ch2.html#dataframes"><i class="fa fa-check"></i><b>2.6.1</b> Dataframes</a></li>
<li class="chapter" data-level="2.6.2" data-path="ch2.html"><a href="ch2.html#loading-data-into-rstudio"><i class="fa fa-check"></i><b>2.6.2</b> Loading data into RStudio</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="ch3.html"><a href="ch3.html"><i class="fa fa-check"></i><b>3</b> Chapter 3: Introduction to network objects</a>
<ul>
<li class="chapter" data-level="3.1" data-path="ch3.html"><a href="ch3.html#what-is-a-network"><i class="fa fa-check"></i><b>3.1</b> What is a network?</a></li>
<li class="chapter" data-level="3.2" data-path="ch3.html"><a href="ch3.html#your-first-network"><i class="fa fa-check"></i><b>3.2</b> Your first network</a></li>
<li class="chapter" data-level="3.3" data-path="ch3.html"><a href="ch3.html#your-second-network"><i class="fa fa-check"></i><b>3.3</b> Your second network</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="ch3.html"><a href="ch3.html#exercise-1"><i class="fa fa-check"></i><b>3.3.1</b> Exercise</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="ch3.html"><a href="ch3.html#node-and-edge-attributes"><i class="fa fa-check"></i><b>3.4</b> Node and edge attributes</a>
<ul>
<li class="chapter" data-level="3.4.1" data-path="ch3.html"><a href="ch3.html#exercise-2"><i class="fa fa-check"></i><b>3.4.1</b> Exercise</a></li>
</ul></li>
<li class="chapter" data-level="3.5" data-path="ch3.html"><a href="ch3.html#graph-attributes"><i class="fa fa-check"></i><b>3.5</b> Graph attributes</a></li>
<li class="chapter" data-level="3.6" data-path="ch3.html"><a href="ch3.html#useful-functions-for-working-with-attributes"><i class="fa fa-check"></i><b>3.6</b> Useful functions for working with attributes</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="ch4.html"><a href="ch4.html"><i class="fa fa-check"></i><b>4</b> Chapter 4: From data to networks</a>
<ul>
<li class="chapter" data-level="4.1" data-path="ch4.html"><a href="ch4.html#how-are-networks-represented"><i class="fa fa-check"></i><b>4.1</b> How are networks represented?</a></li>
<li class="chapter" data-level="4.2" data-path="ch4.html"><a href="ch4.html#edge-list"><i class="fa fa-check"></i><b>4.2</b> Edge List</a></li>
<li class="chapter" data-level="4.3" data-path="ch4.html"><a href="ch4.html#adjacency-matrix"><i class="fa fa-check"></i><b>4.3</b> Adjacency Matrix</a></li>
<li class="chapter" data-level="4.4" data-path="ch4.html"><a href="ch4.html#importing-your-data-and-converting-into-a-network"><i class="fa fa-check"></i><b>4.4</b> Importing your data and converting into a network</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="ch4.html"><a href="ch4.html#importing-edge-lists"><i class="fa fa-check"></i><b>4.4.1</b> Importing edge lists</a></li>
<li class="chapter" data-level="4.4.2" data-path="ch4.html"><a href="ch4.html#importing-adjacency-matrices"><i class="fa fa-check"></i><b>4.4.2</b> Importing adjacency matrices</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="ch4.html"><a href="ch4.html#exercise-3"><i class="fa fa-check"></i><b>4.5</b> Exercise</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="ch5.html"><a href="ch5.html"><i class="fa fa-check"></i><b>5</b> Chapter 5: Manipulating network objects</a>
<ul>
<li class="chapter" data-level="5.1" data-path="ch5.html"><a href="ch5.html#set-up"><i class="fa fa-check"></i><b>5.1</b> Set up</a></li>
<li class="chapter" data-level="5.2" data-path="ch5.html"><a href="ch5.html#adding-node-attributes"><i class="fa fa-check"></i><b>5.2</b> Adding node attributes</a></li>
<li class="chapter" data-level="5.3" data-path="ch5.html"><a href="ch5.html#adding-edge-attributes"><i class="fa fa-check"></i><b>5.3</b> Adding edge attributes</a></li>
<li class="chapter" data-level="5.4" data-path="ch5.html"><a href="ch5.html#subsetting-the-network"><i class="fa fa-check"></i><b>5.4</b> Subsetting the network</a>
<ul>
<li class="chapter" data-level="5.4.1" data-path="ch5.html"><a href="ch5.html#subset-by-node-attributes"><i class="fa fa-check"></i><b>5.4.1</b> Subset by node attributes</a></li>
<li class="chapter" data-level="5.4.2" data-path="ch5.html"><a href="ch5.html#subset-by-a-target-node"><i class="fa fa-check"></i><b>5.4.2</b> Subset by a target node</a></li>
<li class="chapter" data-level="5.4.3" data-path="ch5.html"><a href="ch5.html#subset-by-removing-a-group-of-nodes"><i class="fa fa-check"></i><b>5.4.3</b> Subset by removing a group of nodes</a></li>
<li class="chapter" data-level="5.4.4" data-path="ch5.html"><a href="ch5.html#subset-by-edge-attributes"><i class="fa fa-check"></i><b>5.4.4</b> Subset by edge attributes</a></li>
<li class="chapter" data-level="5.4.5" data-path="ch5.html"><a href="ch5.html#subsetting-by-mutual-edges"><i class="fa fa-check"></i><b>5.4.5</b> Subsetting by mutual edges</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="ch5.html"><a href="ch5.html#useful-functions"><i class="fa fa-check"></i><b>5.5</b> Useful functions</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="ch6.html"><a href="ch6.html"><i class="fa fa-check"></i><b>6</b> Chapter 6: Macro-level network measures</a>
<ul>
<li class="chapter" data-level="6.1" data-path="ch6.html"><a href="ch6.html#average-degree"><i class="fa fa-check"></i><b>6.1</b> Average Degree</a></li>
<li class="chapter" data-level="6.2" data-path="ch6.html"><a href="ch6.html#average-shortest-path-length"><i class="fa fa-check"></i><b>6.2</b> Average Shortest Path Length</a></li>
<li class="chapter" data-level="6.3" data-path="ch6.html"><a href="ch6.html#global-clustering-coefficient"><i class="fa fa-check"></i><b>6.3</b> Global Clustering Coefficient</a></li>
<li class="chapter" data-level="6.4" data-path="ch6.html"><a href="ch6.html#small-world-index"><i class="fa fa-check"></i><b>6.4</b> Small World Index</a></li>
<li class="chapter" data-level="6.5" data-path="ch6.html"><a href="ch6.html#network-density"><i class="fa fa-check"></i><b>6.5</b> Network Density</a></li>
<li class="chapter" data-level="6.6" data-path="ch6.html"><a href="ch6.html#network-diameter"><i class="fa fa-check"></i><b>6.6</b> Network Diameter</a></li>
<li class="chapter" data-level="6.7" data-path="ch6.html"><a href="ch6.html#assortative-mixing"><i class="fa fa-check"></i><b>6.7</b> Assortative Mixing</a>
<ul>
<li class="chapter" data-level="6.7.1" data-path="ch6.html"><a href="ch6.html#assortative-mixing-by-degree-continuous-attributes"><i class="fa fa-check"></i><b>6.7.1</b> Assortative Mixing by Degree (continuous attributes)</a></li>
<li class="chapter" data-level="6.7.2" data-path="ch6.html"><a href="ch6.html#assortative-mixing-by-node-attributes-categorical-attributes"><i class="fa fa-check"></i><b>6.7.2</b> Assortative Mixing by Node Attributes (categorical attributes)</a></li>
</ul></li>
<li class="chapter" data-level="6.8" data-path="ch6.html"><a href="ch6.html#network-components"><i class="fa fa-check"></i><b>6.8</b> Network Components</a></li>
<li class="chapter" data-level="6.9" data-path="ch6.html"><a href="ch6.html#exercise-4"><i class="fa fa-check"></i><b>6.9</b> Exercise</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="ch7.html"><a href="ch7.html"><i class="fa fa-check"></i><b>7</b> Chapter 7: Micro-level network measures</a>
<ul>
<li class="chapter" data-level="7.1" data-path="ch7.html"><a href="ch7.html#degree"><i class="fa fa-check"></i><b>7.1</b> Degree</a>
<ul>
<li class="chapter" data-level="7.1.1" data-path="ch7.html"><a href="ch7.html#in--out--all-degree"><i class="fa fa-check"></i><b>7.1.1</b> In-, out-, all-degree</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="ch7.html"><a href="ch7.html#strength"><i class="fa fa-check"></i><b>7.2</b> Strength</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="ch7.html"><a href="ch7.html#in--out--all-strength"><i class="fa fa-check"></i><b>7.2.1</b> In-, out-, all-strength</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="ch7.html"><a href="ch7.html#local-clustering-coefficient"><i class="fa fa-check"></i><b>7.3</b> Local clustering coefficient</a>
<ul>
<li class="chapter" data-level="7.3.1" data-path="ch7.html"><a href="ch7.html#weighted-local-clustering-coefficient"><i class="fa fa-check"></i><b>7.3.1</b> Weighted local clustering coefficient</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="ch7.html"><a href="ch7.html#closeness-centrality"><i class="fa fa-check"></i><b>7.4</b> Closeness centrality</a>
<ul>
<li class="chapter" data-level="7.4.1" data-path="ch7.html"><a href="ch7.html#weighted-closeness-centrality"><i class="fa fa-check"></i><b>7.4.1</b> Weighted closeness centrality</a></li>
<li class="chapter" data-level="7.4.2" data-path="ch7.html"><a href="ch7.html#interpretation-of-edge-weights"><i class="fa fa-check"></i><b>7.4.2</b> Interpretation of edge weights</a></li>
<li class="chapter" data-level="7.4.3" data-path="ch7.html"><a href="ch7.html#directed-closeness-centrality"><i class="fa fa-check"></i><b>7.4.3</b> Directed closeness centrality</a></li>
</ul></li>
<li class="chapter" data-level="7.5" data-path="ch7.html"><a href="ch7.html#betweenness-centrality"><i class="fa fa-check"></i><b>7.5</b> Betweenness centrality</a>
<ul>
<li class="chapter" data-level="7.5.1" data-path="ch7.html"><a href="ch7.html#weighted-betweenness-centrality"><i class="fa fa-check"></i><b>7.5.1</b> Weighted betweenness centrality</a></li>
<li class="chapter" data-level="7.5.2" data-path="ch7.html"><a href="ch7.html#directed-betweenness-centrality"><i class="fa fa-check"></i><b>7.5.2</b> Directed betweenness centrality</a></li>
</ul></li>
<li class="chapter" data-level="7.6" data-path="ch7.html"><a href="ch7.html#page-rank-centrality"><i class="fa fa-check"></i><b>7.6</b> Page Rank centrality</a></li>
<li class="chapter" data-level="7.7" data-path="ch7.html"><a href="ch7.html#other-forms-of-node-centrality"><i class="fa fa-check"></i><b>7.7</b> Other forms of node centrality</a></li>
<li class="chapter" data-level="7.8" data-path="ch7.html"><a href="ch7.html#exporting-node-centrality-measures-for-data-analysis"><i class="fa fa-check"></i><b>7.8</b> Exporting node centrality measures for data analysis</a></li>
<li class="chapter" data-level="7.9" data-path="ch7.html"><a href="ch7.html#exercise-5"><i class="fa fa-check"></i><b>7.9</b> Exercise</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="ch8.html"><a href="ch8.html"><i class="fa fa-check"></i><b>8</b> Chapter 8: Meso-level network measures</a>
<ul>
<li class="chapter" data-level="8.1" data-path="ch8.html"><a href="ch8.html#how-do-network-scientists-find-communities-in-networks"><i class="fa fa-check"></i><b>8.1</b> How do network scientists “find” communities in networks?</a></li>
<li class="chapter" data-level="8.2" data-path="ch8.html"><a href="ch8.html#edge-betweenness-divisive-method"><i class="fa fa-check"></i><b>8.2</b> Edge betweenness (“divisive method”)</a></li>
<li class="chapter" data-level="8.3" data-path="ch8.html"><a href="ch8.html#louvain-method-greedy-maximization-method"><i class="fa fa-check"></i><b>8.3</b> Louvain method (“greedy, maximization method”)</a></li>
<li class="chapter" data-level="8.4" data-path="ch8.html"><a href="ch8.html#random-walker-dynamic-method"><i class="fa fa-check"></i><b>8.4</b> Random walker (“dynamic method”)</a></li>
<li class="chapter" data-level="8.5" data-path="ch8.html"><a href="ch8.html#infomap-information-theoretic-method"><i class="fa fa-check"></i><b>8.5</b> Infomap (“information-theoretic method”)</a></li>
<li class="chapter" data-level="8.6" data-path="ch8.html"><a href="ch8.html#comparison-of-methods"><i class="fa fa-check"></i><b>8.6</b> Comparison of methods</a>
<ul>
<li class="chapter" data-level="8.6.1" data-path="ch8.html"><a href="ch8.html#comparing-modularity"><i class="fa fa-check"></i><b>8.6.1</b> Comparing modularity</a></li>
<li class="chapter" data-level="8.6.2" data-path="ch8.html"><a href="ch8.html#comparing-community-membership"><i class="fa fa-check"></i><b>8.6.2</b> Comparing community membership</a></li>
</ul></li>
<li class="chapter" data-level="8.7" data-path="ch8.html"><a href="ch8.html#things-to-note"><i class="fa fa-check"></i><b>8.7</b> Things to note</a>
<ul>
<li class="chapter" data-level="8.7.1" data-path="ch8.html"><a href="ch8.html#weighted-and-directed-graphs"><i class="fa fa-check"></i><b>8.7.1</b> Weighted and directed graphs</a></li>
<li class="chapter" data-level="8.7.2" data-path="ch8.html"><a href="ch8.html#networks-with-multiple-components"><i class="fa fa-check"></i><b>8.7.2</b> Networks with multiple components</a></li>
<li class="chapter" data-level="8.7.3" data-path="ch8.html"><a href="ch8.html#calculating-modularity-for-self-defined-communities"><i class="fa fa-check"></i><b>8.7.3</b> Calculating modularity for self-defined communities</a></li>
<li class="chapter" data-level="8.7.4" data-path="ch8.html"><a href="ch8.html#comparing-different-runs"><i class="fa fa-check"></i><b>8.7.4</b> Comparing different runs</a></li>
<li class="chapter" data-level="8.7.5" data-path="ch8.html"><a href="ch8.html#other-community-detection-methods"><i class="fa fa-check"></i><b>8.7.5</b> Other community detection methods</a></li>
</ul></li>
<li class="chapter" data-level="8.8" data-path="ch8.html"><a href="ch8.html#exercise-6"><i class="fa fa-check"></i><b>8.8</b> Exercise</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="ch9.html"><a href="ch9.html"><i class="fa fa-check"></i><b>9</b> Chapter 9: Network models</a></li>
<li class="chapter" data-level="10" data-path="ch10.html"><a href="ch10.html"><i class="fa fa-check"></i><b>10</b> Chapter 10: Behaviors in the network</a>
<ul>
<li class="chapter" data-level="10.1" data-path="ch10.html"><a href="ch10.html#introduction-to-spreadr"><i class="fa fa-check"></i><b>10.1</b> Introduction to <code>spreadr</code></a></li>
<li class="chapter" data-level="10.2" data-path="ch10.html"><a href="ch10.html#case-study-false-memories"><i class="fa fa-check"></i><b>10.2</b> Case study: False memories</a></li>
<li class="chapter" data-level="10.3" data-path="ch10.html"><a href="ch10.html#exercise-design-your-experiment"><i class="fa fa-check"></i><b>10.3</b> Exercise: Design your experiment!</a></li>
<li class="chapter" data-level="10.4" data-path="ch10.html"><a href="ch10.html#references"><i class="fa fa-check"></i><b>10.4</b> References</a></li>
<li class="chapter" data-level="10.5" data-path="ch10.html"><a href="ch10.html#future-topics-under-this-chapter"><i class="fa fa-check"></i><b>10.5</b> Future topics under this chapter</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="ch11.html"><a href="ch11.html"><i class="fa fa-check"></i><b>11</b> Chapter 11: <code>keyplayer</code> package</a>
<ul>
<li class="chapter" data-level="11.1" data-path="ch11.html"><a href="ch11.html#set-up-1"><i class="fa fa-check"></i><b>11.1</b> Set up</a></li>
<li class="chapter" data-level="11.2" data-path="ch11.html"><a href="ch11.html#key-player-problem-negative"><i class="fa fa-check"></i><b>11.2</b> Key Player Problem-Negative</a></li>
<li class="chapter" data-level="11.3" data-path="ch11.html"><a href="ch11.html#key-player-problem-positive"><i class="fa fa-check"></i><b>11.3</b> Key Player Problem-Positive</a></li>
<li class="chapter" data-level="11.4" data-path="ch11.html"><a href="ch11.html#references-1"><i class="fa fa-check"></i><b>11.4</b> References</a></li>
<li class="chapter" data-level="11.5" data-path="ch11.html"><a href="ch11.html#exercise-7"><i class="fa fa-check"></i><b>11.5</b> Exercise</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="ch12.html"><a href="ch12.html"><i class="fa fa-check"></i><b>12</b> Chapter 12: <code>influenceR</code> package</a>
<ul>
<li class="chapter" data-level="12.1" data-path="ch12.html"><a href="ch12.html#set-up-2"><i class="fa fa-check"></i><b>12.1</b> Set up</a></li>
<li class="chapter" data-level="12.2" data-path="ch12.html"><a href="ch12.html#bridging-score"><i class="fa fa-check"></i><b>12.2</b> Bridging score</a>
<ul>
<li class="chapter" data-level="12.2.1" data-path="ch12.html"><a href="ch12.html#important-note-about-directed-graphs"><i class="fa fa-check"></i><b>12.2.1</b> Important note about directed graphs</a></li>
</ul></li>
<li class="chapter" data-level="12.3" data-path="ch12.html"><a href="ch12.html#effective-network-science"><i class="fa fa-check"></i><b>12.3</b> Effective network science</a>
<ul>
<li class="chapter" data-level="12.3.1" data-path="ch12.html"><a href="ch12.html#how-is-effective-network-science-different-from-local-clustering-coefficient"><i class="fa fa-check"></i><b>12.3.1</b> How is effective network science different from local clustering coefficient?</a></li>
<li class="chapter" data-level="12.3.2" data-path="ch12.html"><a href="ch12.html#important-note-about-directed-graphs-1"><i class="fa fa-check"></i><b>12.3.2</b> Important note about directed graphs</a></li>
</ul></li>
<li class="chapter" data-level="12.4" data-path="ch12.html"><a href="ch12.html#references-2"><i class="fa fa-check"></i><b>12.4</b> References</a></li>
<li class="chapter" data-level="12.5" data-path="ch12.html"><a href="ch12.html#exercise-8"><i class="fa fa-check"></i><b>12.5</b> Exercise</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="ch13.html"><a href="ch13.html"><i class="fa fa-check"></i><b>13</b> Chapter 13: <code>bootnet</code> package</a>
<ul>
<li class="chapter" data-level="13.1" data-path="ch13.html"><a href="ch13.html#chapter-outline"><i class="fa fa-check"></i><b>13.1</b> Chapter outline</a></li>
<li class="chapter" data-level="13.2" data-path="ch13.html"><a href="ch13.html#installation-of-bootnet"><i class="fa fa-check"></i><b>13.2</b> Installation of <code>bootnet</code></a>
<ul>
<li class="chapter" data-level="13.2.1" data-path="ch13.html"><a href="ch13.html#qgraph-vs.-igraph"><i class="fa fa-check"></i><b>13.2.1</b> <code>qgraph</code> vs. <code>igraph</code></a></li>
</ul></li>
<li class="chapter" data-level="13.3" data-path="ch13.html"><a href="ch13.html#dataset"><i class="fa fa-check"></i><b>13.3</b> Dataset</a></li>
<li class="chapter" data-level="13.4" data-path="ch13.html"><a href="ch13.html#estimate-a-partial-correlation-network"><i class="fa fa-check"></i><b>13.4</b> Estimate a partial correlation network</a>
<ul>
<li class="chapter" data-level="13.4.1" data-path="ch13.html"><a href="ch13.html#thresholding"><i class="fa fa-check"></i><b>13.4.1</b> Thresholding</a></li>
<li class="chapter" data-level="13.4.2" data-path="ch13.html"><a href="ch13.html#absolutizing"><i class="fa fa-check"></i><b>13.4.2</b> Absolutizing</a></li>
<li class="chapter" data-level="13.4.3" data-path="ch13.html"><a href="ch13.html#conversion-to-igraph"><i class="fa fa-check"></i><b>13.4.3</b> Conversion to igraph</a></li>
</ul></li>
<li class="chapter" data-level="13.5" data-path="ch13.html"><a href="ch13.html#sample-sizes"><i class="fa fa-check"></i><b>13.5</b> Sample sizes</a></li>
<li class="chapter" data-level="13.6" data-path="ch13.html"><a href="ch13.html#additional-resources"><i class="fa fa-check"></i><b>13.6</b> Additional resources</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="ch14.html"><a href="ch14.html"><i class="fa fa-check"></i><b>14</b> Chapter 14: Network visualization in <code>igraph</code></a>
<ul>
<li class="chapter" data-level="14.1" data-path="ch14.html"><a href="ch14.html#set-up-3"><i class="fa fa-check"></i><b>14.1</b> Set up</a></li>
<li class="chapter" data-level="14.2" data-path="ch14.html"><a href="ch14.html#visualizing-node-attributes"><i class="fa fa-check"></i><b>14.2</b> Visualizing node attributes</a>
<ul>
<li class="chapter" data-level="14.2.1" data-path="ch14.html"><a href="ch14.html#color-nodes-by-their-categorical-attributes"><i class="fa fa-check"></i><b>14.2.1</b> Color nodes by their categorical attributes</a></li>
<li class="chapter" data-level="14.2.2" data-path="ch14.html"><a href="ch14.html#color-nodes-by-their-continuous-attributes"><i class="fa fa-check"></i><b>14.2.2</b> Color nodes by their continuous attributes</a></li>
<li class="chapter" data-level="14.2.3" data-path="ch14.html"><a href="ch14.html#node-shapes-by-their-categorical-attributes"><i class="fa fa-check"></i><b>14.2.3</b> Node shapes by their categorical attributes</a></li>
<li class="chapter" data-level="14.2.4" data-path="ch14.html"><a href="ch14.html#node-size-by-their-continuous-attributes"><i class="fa fa-check"></i><b>14.2.4</b> Node size by their continuous attributes</a></li>
<li class="chapter" data-level="14.2.5" data-path="ch14.html"><a href="ch14.html#example-1-color-nodes-by-their-community-membership"><i class="fa fa-check"></i><b>14.2.5</b> Example 1: Color nodes by their community membership</a></li>
<li class="chapter" data-level="14.2.6" data-path="ch14.html"><a href="ch14.html#example-2-size-nodes-by-their-degree"><i class="fa fa-check"></i><b>14.2.6</b> Example 2: Size nodes by their degree</a></li>
</ul></li>
<li class="chapter" data-level="14.3" data-path="ch14.html"><a href="ch14.html#visualizing-edge-attributes"><i class="fa fa-check"></i><b>14.3</b> Visualizing edge attributes</a>
<ul>
<li class="chapter" data-level="14.3.1" data-path="ch14.html"><a href="ch14.html#color-edges-by-their-categorical-attributes"><i class="fa fa-check"></i><b>14.3.1</b> Color edges by their categorical attributes</a></li>
<li class="chapter" data-level="14.3.2" data-path="ch14.html"><a href="ch14.html#edge-thickness-based-on-their-continuous-attributes"><i class="fa fa-check"></i><b>14.3.2</b> Edge thickness based on their continuous attributes</a></li>
<li class="chapter" data-level="14.3.3" data-path="ch14.html"><a href="ch14.html#arrows-for-directed-edges"><i class="fa fa-check"></i><b>14.3.3</b> Arrows for directed edges</a></li>
</ul></li>
<li class="chapter" data-level="14.4" data-path="ch14.html"><a href="ch14.html#other"><i class="fa fa-check"></i><b>14.4</b> Other</a>
<ul>
<li class="chapter" data-level="14.4.1" data-path="ch14.html"><a href="ch14.html#graph-layouts"><i class="fa fa-check"></i><b>14.4.1</b> Graph layouts</a></li>
<li class="chapter" data-level="14.4.2" data-path="ch14.html"><a href="ch14.html#plot-title"><i class="fa fa-check"></i><b>14.4.2</b> Plot title</a></li>
<li class="chapter" data-level="14.4.3" data-path="ch14.html"><a href="ch14.html#add-a-subtitle"><i class="fa fa-check"></i><b>14.4.3</b> Add a subtitle</a></li>
<li class="chapter" data-level="14.4.4" data-path="ch14.html"><a href="ch14.html#multiple-plots"><i class="fa fa-check"></i><b>14.4.4</b> Multiple plots</a></li>
<li class="chapter" data-level="14.4.5" data-path="ch14.html"><a href="ch14.html#useful-links"><i class="fa fa-check"></i><b>14.4.5</b> Useful links</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="15" data-path="ch15.html"><a href="ch15.html"><i class="fa fa-check"></i><b>15</b> Chapter 15: Network visualization with other packages</a></li>
<li class="chapter" data-level="16" data-path="ch16.html"><a href="ch16.html"><i class="fa fa-check"></i><b>16</b> Chapter 16: Analyzing degree distributions</a>
<ul>
<li class="chapter" data-level="16.1" data-path="ch16.html"><a href="ch16.html#set-up-4"><i class="fa fa-check"></i><b>16.1</b> Set up</a></li>
<li class="chapter" data-level="16.2" data-path="ch16.html"><a href="ch16.html#fitting-the-power-law-distribution"><i class="fa fa-check"></i><b>16.2</b> Fitting the power law distribution</a></li>
<li class="chapter" data-level="16.3" data-path="ch16.html"><a href="ch16.html#visualization"><i class="fa fa-check"></i><b>16.3</b> Visualization</a></li>
<li class="chapter" data-level="16.4" data-path="ch16.html"><a href="ch16.html#statistical-testing-of-distribution-fit"><i class="fa fa-check"></i><b>16.4</b> Statistical testing of distribution fit</a>
<ul>
<li class="chapter" data-level="16.4.1" data-path="ch16.html"><a href="ch16.html#method-1-bootstrapping-the-data"><i class="fa fa-check"></i><b>16.4.1</b> Method 1: Bootstrapping the data</a></li>
<li class="chapter" data-level="16.4.2" data-path="ch16.html"><a href="ch16.html#method-2-comparing-alternative-distributions"><i class="fa fa-check"></i><b>16.4.2</b> Method 2: Comparing alternative distributions</a></li>
</ul></li>
<li class="chapter" data-level="16.5" data-path="ch16.html"><a href="ch16.html#exercise-9"><i class="fa fa-check"></i><b>16.5</b> Exercise</a></li>
<li class="chapter" data-level="16.6" data-path="ch16.html"><a href="ch16.html#references-3"><i class="fa fa-check"></i><b>16.6</b> References</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Introduction to Network Analysis in <code>igraph</code></a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="ch6" class="section level1 hasAnchor" number="6">
<h1><span class="header-section-number">Chapter 6</span> Chapter 6: Macro-level network measures<a href="ch6.html#ch6" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>In this section, we will review network science measures that describe the overall or global structure of the entire network. You can think of these measures as providing a “bird’s eye view” of your network, and they are useful for comparing different network representations.</p>
<p>To facilitate the demonstrations below, we will use the undirected, unweighted karate network that we have previously seen in Chapter 4. In the rest of the chapter we will compute various macro-level network measures for this network.</p>
<div class="sourceCode" id="cb150"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb150-1"><a href="ch6.html#cb150-1" tabindex="-1"></a>karate_el <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&#39;data/karate_el.csv&#39;</span>, <span class="at">header =</span> <span class="cn">FALSE</span>)</span>
<span id="cb150-2"><a href="ch6.html#cb150-2" tabindex="-1"></a></span>
<span id="cb150-3"><a href="ch6.html#cb150-3" tabindex="-1"></a>karate_uu <span class="ot">&lt;-</span> <span class="fu">graph_from_data_frame</span>(karate_el, <span class="at">directed =</span> <span class="cn">FALSE</span>)</span>
<span id="cb150-4"><a href="ch6.html#cb150-4" tabindex="-1"></a></span>
<span id="cb150-5"><a href="ch6.html#cb150-5" tabindex="-1"></a><span class="fu">summary</span>(karate_uu)</span></code></pre></div>
<pre><code>## IGRAPH 942edc6 UN-- 34 78 -- 
## + attr: name (v/c)</code></pre>
<p>Although it is possible to compute macro-level network measures for directed, weighted networks in certain instances (and this will be pointed out where appropriate), I choose to focus on the undirected, unweighted version for this chapter because macro-level measures are more complex to interpret and less intuitive when additional information like edge weights and direction are included. For instance, <em>network density</em> refers to the ratio of the number of (existing) edges and the number of possible edges among nodes in the network–it is not clear how this measure be adapted if we wanted to use weighted edges instead.</p>
<div id="average-degree" class="section level2 hasAnchor" number="6.1">
<h2><span class="header-section-number">6.1</span> Average Degree<a href="ch6.html#average-degree" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>A common method of characterizing the global structure of networks is to simply compute <strong>average degree</strong>, which is the mean of the degree of all nodes in the network. A node’s degree refers to the number of connections or edges that are incident to the node.</p>
<p>We first use <code>degree</code> to compute degree for each node (see Chapter 7: Degree) and then pipe the output to get the mean degree for the entire network.</p>
<div class="sourceCode" id="cb152"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb152-1"><a href="ch6.html#cb152-1" tabindex="-1"></a><span class="fu">degree</span>(karate_uu) <span class="sc">|&gt;</span> <span class="fu">mean</span>()</span></code></pre></div>
<pre><code>## [1] 4.588235</code></pre>
<p>On average, each node in the karate network has 4.5 connections.</p>
<p>In Chapter 7 we will learn that it is possible to compute different variants of degree for directed graphs. In-degree refers to the number of edges incoming to the target node, out-degree refers to the number of edges outgoing from to the target node, and all-degree refers to all the edges (the sum of in- and out-degree). Try running the code below on a network with directed edges.</p>
<div class="sourceCode" id="cb154"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb154-1"><a href="ch6.html#cb154-1" tabindex="-1"></a><span class="co"># mean in-degree</span></span>
<span id="cb154-2"><a href="ch6.html#cb154-2" tabindex="-1"></a><span class="fu">degree</span>(karate_uu, <span class="at">mode =</span> <span class="st">&#39;in&#39;</span>) <span class="sc">|&gt;</span> <span class="fu">mean</span>()</span>
<span id="cb154-3"><a href="ch6.html#cb154-3" tabindex="-1"></a></span>
<span id="cb154-4"><a href="ch6.html#cb154-4" tabindex="-1"></a><span class="co"># mean out-degree</span></span>
<span id="cb154-5"><a href="ch6.html#cb154-5" tabindex="-1"></a><span class="fu">degree</span>(karate_uu, <span class="at">mode =</span> <span class="st">&#39;out&#39;</span>) <span class="sc">|&gt;</span> <span class="fu">mean</span>()</span>
<span id="cb154-6"><a href="ch6.html#cb154-6" tabindex="-1"></a></span>
<span id="cb154-7"><a href="ch6.html#cb154-7" tabindex="-1"></a><span class="co"># mean all-degree</span></span>
<span id="cb154-8"><a href="ch6.html#cb154-8" tabindex="-1"></a><span class="fu">degree</span>(karate_uu, <span class="at">mode =</span> <span class="st">&#39;all&#39;</span>) <span class="sc">|&gt;</span> <span class="fu">mean</span>()</span></code></pre></div>
</div>
<div id="average-shortest-path-length" class="section level2 hasAnchor" number="6.2">
<h2><span class="header-section-number">6.2</span> Average Shortest Path Length<a href="ch6.html#average-shortest-path-length" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p><strong>Average shortest path length</strong> (ASPL) refers to the mean of the shortest possible path between all possible pairs of nodes in the network. (This loosely corresponds to the idea of “six degrees of separation” in social networks.)</p>
<p>The figure below depicts the shortest path between nodes 25 and 16 (path length = 4).</p>
<p><img src="images/shortest-path.jpeg" /></p>
<p>To compute the ASPL of the karate network:</p>
<div class="sourceCode" id="cb155"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb155-1"><a href="ch6.html#cb155-1" tabindex="-1"></a><span class="fu">mean_distance</span>(<span class="at">graph =</span> karate_uu)</span></code></pre></div>
<pre><code>## [1] 2.4082</code></pre>
<p>On average, it takes 2.4 steps to connect any two randomly selected nodes in the karate network.</p>
<p>It is possible to compute ASPL based on shortest paths that consider the direction and weights of the edges.</p>
<div class="sourceCode" id="cb157"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb157-1"><a href="ch6.html#cb157-1" tabindex="-1"></a><span class="fu">mean_distance</span>(karate_uu, <span class="at">weights =</span> <span class="cn">NA</span>, <span class="at">directed =</span> F) <span class="co"># unweighted, undirected</span></span></code></pre></div>
<pre><code>## [1] 2.4082</code></pre>
<div class="sourceCode" id="cb159"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb159-1"><a href="ch6.html#cb159-1" tabindex="-1"></a><span class="fu">mean_distance</span>(karate_uu, <span class="at">weights =</span> <span class="cn">NA</span>, <span class="at">directed =</span> T) <span class="co"># unweighted, directed </span></span></code></pre></div>
<pre><code>## [1] 2.4082</code></pre>
<div class="sourceCode" id="cb161"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb161-1"><a href="ch6.html#cb161-1" tabindex="-1"></a><span class="fu">mean_distance</span>(karate_uu, <span class="at">directed =</span> F) <span class="co"># weighted, undirected</span></span></code></pre></div>
<pre><code>## [1] 2.4082</code></pre>
<div class="sourceCode" id="cb163"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb163-1"><a href="ch6.html#cb163-1" tabindex="-1"></a><span class="fu">mean_distance</span>(karate_uu, <span class="at">directed =</span> T) <span class="co"># weighted, directed </span></span></code></pre></div>
<pre><code>## [1] 2.4082</code></pre>
<p>Because <code>karate_uu</code> is undirected and unweighted, the result is unsurprisingly identical across all 4 version (try this with a directed, weighted network!). When a graph contains edge weights, then they are automatically considered unless you instruct otherwise using <code>weights = NA</code>. Use the <code>directed</code> argument to specify if the direction of the edges should be considered in the computation of short paths.</p>
<p>An important point to note is that edge weights are interpreted as <em>distances</em> rather than <em>strength of connection</em>: See Chapter 7 for more information about this.</p>
</div>
<div id="global-clustering-coefficient" class="section level2 hasAnchor" number="6.3">
<h2><span class="header-section-number">6.3</span> Global Clustering Coefficient<a href="ch6.html#global-clustering-coefficient" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p><strong>Global clustering coefficient</strong>, or global <em>C</em>, refers to the number of closed triangles in the network relative to the number of possible triangles. It is a measure of overall level of local connectivity among nodes in the network.</p>
<p>A simple way of thinking about this concept is that it is measuring the probability that each pair of “friends” of a given node are also friends with each other.</p>
<p>To computer global clustering coefficient, we use the <code>transitivity</code> function as follows:</p>
<div class="sourceCode" id="cb165"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb165-1"><a href="ch6.html#cb165-1" tabindex="-1"></a><span class="fu">transitivity</span>(karate_uu, <span class="at">type =</span> <span class="st">&#39;global&#39;</span>)</span></code></pre></div>
<pre><code>## [1] 0.2556818</code></pre>
<p>We can interpret this value to mean that for each pair of nodes that are directly connected to a target node, the probability that these two nodes are also connected to each other is 25.6% (i.e., the probability of a completed “triangle”, when it is possible, is 25.6%). This value is usually quite high in social networks, because people tend to introduce their friends to each other, resulting in <em>triadic closure</em>.</p>
<p>Contrast this with Chapter 7: Local clustering coefficient–notice that although we use the same function, the <code>type</code> argument specifies if we want to obtain the global clustering coefficient for the whole network (overall local connectivity), or local clustering coefficient for individual nodes (local connectivity centered on a single node).</p>
</div>
<div id="small-world-index" class="section level2 hasAnchor" number="6.4">
<h2><span class="header-section-number">6.4</span> Small World Index<a href="ch6.html#small-world-index" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The term “small world” has a specific meaning in network science as compared to the layperson’s. A network is considered to have small world characteristics if (i) its ASPL is shorter than that of a randomly generated network with the same number of nodes and edges, and (ii) its global <em>C</em> is larger than that of a randomly generated network with the same number of nodes and edges. There are various ways to compute a value that quantifies the “small worldness” of a network, although we do not cover all of them here (see Neal, 2017, for a comparison of different methods). In this section we go through an approach to quantifying small-worldness based on Humphries and Gurney (2008).</p>
<p>In practice, researchers compute a measure known as the <strong>small world index</strong> which combines the global clustering coefficient and ASPL of the target network relative to its equally sized random graphs (with the same number of nodes and edges) to derive a proportional score.</p>
<p>Mathematically,
<span class="math display">\[SWI = \frac{C_i / \overline C_{rand}}{L_i / \overline L_{rand}}\]</span>
where <em>C</em> = global clustering coefficient, <em>L</em> = average shortest path length, <em>i</em> = network of interest, <em>rand</em> = random network, <span class="math inline">\(\overline x\)</span> denotes mean of the random networks’ measures.</p>
<p>In order to compute the Small World Index we need to first generate networks that form a baseline for comparison to the target network (see also Chapter 9: Network Models). Here, we generate 5 size-matched Erdos-Renyi (ER) networks, which is a type of random network model where edges are distributed randomly across a set of nodes. We specify that the number of nodes and edges of the ER network to be identical to the target network (<code>karate_uu</code>). Then we take the mean ASPL and C of the ER networks, which becomes the <span class="math inline">\(\overline L_{rand}\)</span> and <span class="math inline">\(\overline C_{rand}\)</span> in the equation above respectively.</p>
<div class="sourceCode" id="cb167"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb167-1"><a href="ch6.html#cb167-1" tabindex="-1"></a><span class="do">## generate ER networks </span></span>
<span id="cb167-2"><a href="ch6.html#cb167-2" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">2</span>)</span>
<span id="cb167-3"><a href="ch6.html#cb167-3" tabindex="-1"></a></span>
<span id="cb167-4"><a href="ch6.html#cb167-4" tabindex="-1"></a>er_graphs <span class="ot">&lt;-</span> <span class="fu">list</span>()</span>
<span id="cb167-5"><a href="ch6.html#cb167-5" tabindex="-1"></a></span>
<span id="cb167-6"><a href="ch6.html#cb167-6" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>) { <span class="co"># number of networks to generate</span></span>
<span id="cb167-7"><a href="ch6.html#cb167-7" tabindex="-1"></a>  er_graphs[[i]] <span class="ot">&lt;-</span> <span class="fu">sample_gnm</span>(<span class="at">n =</span> <span class="fu">gorder</span>(karate_uu), <span class="at">m =</span> <span class="fu">gsize</span>(karate_uu), <span class="at">directed =</span> F, <span class="at">loops =</span> F)</span>
<span id="cb167-8"><a href="ch6.html#cb167-8" tabindex="-1"></a>}</span>
<span id="cb167-9"><a href="ch6.html#cb167-9" tabindex="-1"></a></span>
<span id="cb167-10"><a href="ch6.html#cb167-10" tabindex="-1"></a><span class="co"># compute the L and C for each ER network, take the mean </span></span>
<span id="cb167-11"><a href="ch6.html#cb167-11" tabindex="-1"></a><span class="fu">sapply</span>(er_graphs, mean_distance) <span class="sc">|&gt;</span> <span class="fu">mean</span>() <span class="co"># L_rand</span></span></code></pre></div>
<pre><code>## [1] 2.384314</code></pre>
<div class="sourceCode" id="cb169"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb169-1"><a href="ch6.html#cb169-1" tabindex="-1"></a><span class="fu">sapply</span>(er_graphs, transitivity, <span class="at">type =</span> <span class="st">&#39;global&#39;</span>) <span class="sc">|&gt;</span> <span class="fu">mean</span>() <span class="co"># C_rand</span></span></code></pre></div>
<pre><code>## [1] 0.1188022</code></pre>
<p>We can now plug in these values together with the actual C and L of the target network to compute SWI:</p>
<div class="sourceCode" id="cb171"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb171-1"><a href="ch6.html#cb171-1" tabindex="-1"></a><span class="co"># SWI for karate_uu </span></span>
<span id="cb171-2"><a href="ch6.html#cb171-2" tabindex="-1"></a>(<span class="fl">0.2556818</span><span class="sc">/</span><span class="fl">0.1188022</span>)<span class="sc">/</span>(<span class="fl">2.4082</span><span class="sc">/</span><span class="fl">2.384314</span>)</span></code></pre></div>
<pre><code>## [1] 2.130817</code></pre>
<p>Humphries and Gurney (2008) write that SWI larger than 1 indicates presence of a small world structure, since this implies that the target network has more local clustering than random expectation, while having relatively similar ASPLs. SWIs less than 1 or close to 1 indicates that there is no evidence to support the claim that the target network is a small world. Here, we have some evidence supporting the claim that our karate network has a small world structure. In practice, up to 1,000 random ER networks are generated to compute <span class="math inline">\(\overline L_{rand}\)</span> and <span class="math inline">\(\overline C_{rand}\)</span>; although this can be a slow process depending on your network size. The number of random networks to generate can be adjusted in the for loop above.</p>
<p>The main take home message is that a small world network has high levels of local clustering (nodes whose neighbors are also neighbors of each other), but also contains a number of shortcuts that drastically reduces the overall distances/path lengths between nodes. See below for an illustration of this idea.</p>
<p><img src="images/small-world.png" /></p>
</div>
<div id="network-density" class="section level2 hasAnchor" number="6.5">
<h2><span class="header-section-number">6.5</span> Network Density<a href="ch6.html#network-density" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p><strong>Network density</strong> refers to the ratio of the number of (existing) edges and the number of possible edges among nodes in the network.</p>
<p>Simple example of networks with lower and higher network densities.</p>
<p><img src="images/density.png" /></p>
<p>To obtain network density of a network:</p>
<div class="sourceCode" id="cb173"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb173-1"><a href="ch6.html#cb173-1" tabindex="-1"></a><span class="fu">edge_density</span>(karate_uu)</span></code></pre></div>
<pre><code>## [1] 0.1390374</code></pre>
<p>This means that 13.9% of all possible edges in the network are actual edges.</p>
</div>
<div id="network-diameter" class="section level2 hasAnchor" number="6.6">
<h2><span class="header-section-number">6.6</span> Network Diameter<a href="ch6.html#network-diameter" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Network diameter refers to length of the longest shortest path between nodes in the network. Instead of getting the mean of all the shortest paths as you did in ASPL, what is the maximum length of those short paths?</p>
<p>Simple example of networks with higher and lower network diameters</p>
<p><img src="images/diameter.png" /></p>
<p>To obtain network diameter of a network:</p>
<div class="sourceCode" id="cb175"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb175-1"><a href="ch6.html#cb175-1" tabindex="-1"></a><span class="fu">diameter</span>(karate_uu, <span class="at">directed =</span> F)</span></code></pre></div>
<pre><code>## [1] 5</code></pre>
<div class="sourceCode" id="cb177"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb177-1"><a href="ch6.html#cb177-1" tabindex="-1"></a><span class="co"># diameter(karate_uu, directed = T) # directed edges </span></span></code></pre></div>
<p>This means that the length of the longest shortest path between two nodes in the network is 5.</p>
</div>
<div id="assortative-mixing" class="section level2 hasAnchor" number="6.7">
<h2><span class="header-section-number">6.7</span> Assortative Mixing<a href="ch6.html#assortative-mixing" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p><strong>Assortative mixing</strong> is a measure of <em>homophily</em> in the network, based on some internal/external property of the nodes. Are nodes that are connected to each other tend to have similar properties?</p>
<div id="assortative-mixing-by-degree-continuous-attributes" class="section level3 hasAnchor" number="6.7.1">
<h3><span class="header-section-number">6.7.1</span> Assortative Mixing by Degree (continuous attributes)<a href="ch6.html#assortative-mixing-by-degree-continuous-attributes" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>A common extension of assortative mixing is <strong>assortative mixing by degree</strong>, which measures the correlation of degrees between neighboring nodes. Are nodes that are connected to each other tend to have similar degrees?</p>
<p>A positive value indicates that nodes that are many (few) neighbors tend to be connected to nodes that also have many (few) neighbors. A negative value indicates that nodes that are many (few) neighbors tend to be connected to nodes that have few (many) neighbors. Values very close to zero indicates no correlation.</p>
<div class="sourceCode" id="cb178"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb178-1"><a href="ch6.html#cb178-1" tabindex="-1"></a><span class="fu">assortativity_degree</span>(karate_uu, <span class="at">directed =</span> F)</span></code></pre></div>
<pre><code>## [1] -0.4756131</code></pre>
<div class="sourceCode" id="cb180"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb180-1"><a href="ch6.html#cb180-1" tabindex="-1"></a><span class="co"># assortativity_degree(karate_uu, directed = T) # for directed edges </span></span></code></pre></div>
<p>There is <em>dissortativity mixing by degree</em> in the karate network–nodes with higher degree have a higher tendency to be connected to nodes with lower degree.</p>
<p>It is possible to add your own node attributes to the network (see Chapter 5) and compute its assortativity. The script below demonstrates this with a randomly created set of numbers for the nodes (i.e., a continuous variable ranging from 1 to 5, randomly selected with replacement for each of the 34 nodes in the network). Because these numbers are randomly generated, we expect assortativity to be close to 0 here.</p>
<div class="sourceCode" id="cb181"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb181-1"><a href="ch6.html#cb181-1" tabindex="-1"></a><span class="co"># create a random vector of numbers for demonstration</span></span>
<span id="cb181-2"><a href="ch6.html#cb181-2" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">3</span>)</span>
<span id="cb181-3"><a href="ch6.html#cb181-3" tabindex="-1"></a><span class="fu">V</span>(karate_uu)<span class="sc">$</span>random1 <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>, <span class="fu">gorder</span>(karate_uu), <span class="at">replace =</span> T)</span>
<span id="cb181-4"><a href="ch6.html#cb181-4" tabindex="-1"></a></span>
<span id="cb181-5"><a href="ch6.html#cb181-5" tabindex="-1"></a><span class="co"># compute the assortativity of this node attribute </span></span>
<span id="cb181-6"><a href="ch6.html#cb181-6" tabindex="-1"></a><span class="fu">assortativity</span>(karate_uu, <span class="at">values =</span> <span class="fu">V</span>(karate_uu)<span class="sc">$</span>random1, <span class="at">directed =</span> F)</span></code></pre></div>
<pre><code>## [1] -0.06819853</code></pre>
</div>
<div id="assortative-mixing-by-node-attributes-categorical-attributes" class="section level3 hasAnchor" number="6.7.2">
<h3><span class="header-section-number">6.7.2</span> Assortative Mixing by Node Attributes (categorical attributes)<a href="ch6.html#assortative-mixing-by-node-attributes-categorical-attributes" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>It is also possible to compute assortativity for categorical labels assigned to nodes. For instance, in a social network of male and female actors, is there gender homophily such that nodes tend to be connected to other nodes that share the same label?</p>
<p>A positive value indicates that nodes with the same labels tend to be connected to each other. A negative value indicates that nodes tend to be connected to nodes with a different label from itself. Values very close to zero indicates no correlation.</p>
<p>It is possible to add your own node attributes to the network (see Chapter 5) and compute its assortativity. The script below demonstrates this with a randomly created set of labels for the nodes (i.e., a categorical variable). Because these labels are randomly generated, we expect assortativity to be close to 0 here.</p>
<div class="sourceCode" id="cb183"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb183-1"><a href="ch6.html#cb183-1" tabindex="-1"></a><span class="co"># create a random vector of labels for demonstration</span></span>
<span id="cb183-2"><a href="ch6.html#cb183-2" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">3</span>)</span>
<span id="cb183-3"><a href="ch6.html#cb183-3" tabindex="-1"></a><span class="fu">V</span>(karate_uu)<span class="sc">$</span>random2 <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="fu">c</span>(<span class="st">&#39;A&#39;</span>, <span class="st">&#39;B&#39;</span>, <span class="st">&#39;C&#39;</span>), <span class="fu">gorder</span>(karate_uu), <span class="at">replace =</span> T)</span>
<span id="cb183-4"><a href="ch6.html#cb183-4" tabindex="-1"></a></span>
<span id="cb183-5"><a href="ch6.html#cb183-5" tabindex="-1"></a><span class="co"># compute the assortativity of this node attribute </span></span>
<span id="cb183-6"><a href="ch6.html#cb183-6" tabindex="-1"></a><span class="fu">assortativity_nominal</span>(karate_uu, <span class="at">types =</span> <span class="fu">factor</span>(<span class="fu">V</span>(karate_uu)<span class="sc">$</span>random2), <span class="at">directed =</span> F)</span></code></pre></div>
<pre><code>## [1] -0.0850826</code></pre>
</div>
</div>
<div id="network-components" class="section level2 hasAnchor" number="6.8">
<h2><span class="header-section-number">6.8</span> Network Components<a href="ch6.html#network-components" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Thus far, we have been assuming that the networks that we have worked with form a single component. In other words, all nodes are part of the same component, and there are no separate components. But, as shown in the example network below, it is certainly possible for nodes in a network to fragment into distinct components.</p>
<div class="sourceCode" id="cb185"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb185-1"><a href="ch6.html#cb185-1" tabindex="-1"></a><span class="co"># create a sample network with two distinct components </span></span>
<span id="cb185-2"><a href="ch6.html#cb185-2" tabindex="-1"></a>g <span class="ot">&lt;-</span> <span class="fu">graph_from_literal</span>(A<span class="sc">-</span>B, B<span class="sc">-</span>C, A<span class="sc">-</span>C, D<span class="sc">-</span>E)</span>
<span id="cb185-3"><a href="ch6.html#cb185-3" tabindex="-1"></a><span class="fu">plot</span>(g)</span></code></pre></div>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-68-1.png" width="672" /></p>
<p>When working with networks derived from behavioral data, it can be common to observe that the network consists of distinct network components. This has implications for the computing and interpretation of the macro-level network measures, because several of them rely on the computation of shortest path between node pairs. For instance, ASPL computes the shortest paths for all possible node pairs and takes the mean–but what happens if there is no path between nodes A and D, for example?</p>
<p>Node pairs that do not have a path are ignored in the computation. This is the default behavior in <code>igraph</code>. Hence, this value reflects the mean of all “computable” short paths (i.e., when node pairs are found in the same component) and this is computed across all network components in the network.</p>
<div class="sourceCode" id="cb186"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb186-1"><a href="ch6.html#cb186-1" tabindex="-1"></a><span class="fu">mean_distance</span>(g, <span class="at">unconnected =</span> <span class="cn">TRUE</span>) <span class="co"># ignore infinite paths, default </span></span></code></pre></div>
<pre><code>## [1] 1</code></pre>
<div class="sourceCode" id="cb188"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb188-1"><a href="ch6.html#cb188-1" tabindex="-1"></a><span class="fu">mean_distance</span>(g, <span class="at">unconnected =</span> <span class="cn">FALSE</span>) <span class="co"># consider infinite paths </span></span></code></pre></div>
<pre><code>## [1] Inf</code></pre>
<p>As you can see, the second output is <code>Inf</code>, reflecting the presence of infinite paths in the network. From the <code>igraph</code> documentation: “If TRUE, only the lengths of the existing paths are considered and averaged; if FALSE, the length of the missing paths are considered as having infinite length, making the mean distance infinite as well.”</p>
<p>Hence, it is good practice to first check if your network consists of a single component, or multiple components. We can use the following script to find out: how many components, the size of each components (number of nodes), and obtain a list of nodes and their component membership. Basically, <code>components</code> is a special function that stores these pieces of information as its output, which you can then retrieve using the <code>$</code>: <code>csize</code> for size of component, <code>no</code> for number of components, <code>membership</code> for the component membership for each node.</p>
<div class="sourceCode" id="cb190"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb190-1"><a href="ch6.html#cb190-1" tabindex="-1"></a>g_comp <span class="ot">&lt;-</span> <span class="fu">components</span>(g)</span>
<span id="cb190-2"><a href="ch6.html#cb190-2" tabindex="-1"></a></span>
<span id="cb190-3"><a href="ch6.html#cb190-3" tabindex="-1"></a>g_comp<span class="sc">$</span>csize <span class="co"># size of each component </span></span></code></pre></div>
<pre><code>## [1] 3 2</code></pre>
<div class="sourceCode" id="cb192"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb192-1"><a href="ch6.html#cb192-1" tabindex="-1"></a>g_comp<span class="sc">$</span>no <span class="co"># number of components </span></span></code></pre></div>
<pre><code>## [1] 2</code></pre>
<div class="sourceCode" id="cb194"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb194-1"><a href="ch6.html#cb194-1" tabindex="-1"></a><span class="fu">data.frame</span>(<span class="at">node =</span> <span class="fu">V</span>(g)<span class="sc">$</span>name, <span class="at">membership =</span> g_comp<span class="sc">$</span>membership)</span></code></pre></div>
<pre><code>##   node membership
## A    A          1
## B    B          1
## C    C          1
## D    D          2
## E    E          2</code></pre>
<div class="sourceCode" id="cb196"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb196-1"><a href="ch6.html#cb196-1" tabindex="-1"></a><span class="co"># you should know how to export the results into a .csv file! </span></span></code></pre></div>
<p>Typically, real-world networks have a giant or largest connected component (LCC) which contains the majority of nodes in the network, and researchers prefer to only compute network-level metrics on the LCC. This component is extracted for further analysis, removing the smaller connected components or hermits (isolates in the network where the node has no neighbors).</p>
<p>The code below shows you how to extract the largest connected component of the sample network:</p>
<div class="sourceCode" id="cb197"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb197-1"><a href="ch6.html#cb197-1" tabindex="-1"></a>g_lcc <span class="ot">&lt;-</span> <span class="fu">induced_subgraph</span>(<span class="at">graph =</span> g, </span>
<span id="cb197-2"><a href="ch6.html#cb197-2" tabindex="-1"></a>                          <span class="at">vids =</span> <span class="fu">components</span>(g)<span class="sc">$</span>membership <span class="sc">==</span> <span class="fu">which.max</span>(<span class="fu">components</span>(g)<span class="sc">$</span>csize)) </span>
<span id="cb197-3"><a href="ch6.html#cb197-3" tabindex="-1"></a></span>
<span id="cb197-4"><a href="ch6.html#cb197-4" tabindex="-1"></a><span class="fu">summary</span>(g_lcc)</span></code></pre></div>
<pre><code>## IGRAPH 06bc357 UN-- 3 3 -- 
## + attr: name (v/c)</code></pre>
<p>It is also possible to extract other components of the network. The code below retains nodes that do not belong to the largest connected component of the network.</p>
<div class="sourceCode" id="cb199"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb199-1"><a href="ch6.html#cb199-1" tabindex="-1"></a>g_2 <span class="ot">&lt;-</span> <span class="fu">induced_subgraph</span>(<span class="at">graph =</span> g, </span>
<span id="cb199-2"><a href="ch6.html#cb199-2" tabindex="-1"></a>                          <span class="at">vids =</span> <span class="fu">components</span>(g)<span class="sc">$</span>membership <span class="sc">!=</span> <span class="fu">which.max</span>(<span class="fu">components</span>(g)<span class="sc">$</span>csize)) </span>
<span id="cb199-3"><a href="ch6.html#cb199-3" tabindex="-1"></a></span>
<span id="cb199-4"><a href="ch6.html#cb199-4" tabindex="-1"></a><span class="fu">summary</span>(g_2)</span></code></pre></div>
<pre><code>## IGRAPH ec57f4e UN-- 2 1 -- 
## + attr: name (v/c)</code></pre>
</div>
<div id="exercise-4" class="section level2 hasAnchor" number="6.9">
<h2><span class="header-section-number">6.9</span> Exercise<a href="ch6.html#exercise-4" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Your task is to:</p>
<ol style="list-style-type: decimal">
<li>Load the <code>UKfaculty</code> network from the <code>igraphdata</code> library using the following code:</li>
</ol>
<div class="sourceCode" id="cb201"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb201-1"><a href="ch6.html#cb201-1" tabindex="-1"></a><span class="fu">library</span>(igraphdata) <span class="co"># have you downloaded the package? </span></span>
<span id="cb201-2"><a href="ch6.html#cb201-2" tabindex="-1"></a></span>
<span id="cb201-3"><a href="ch6.html#cb201-3" tabindex="-1"></a><span class="fu">data</span>(<span class="st">&quot;UKfaculty&quot;</span>) <span class="co"># you should see a UKfaculty object appear in your Environment</span></span>
<span id="cb201-4"><a href="ch6.html#cb201-4" tabindex="-1"></a></span>
<span id="cb201-5"><a href="ch6.html#cb201-5" tabindex="-1"></a><span class="co"># I&#39;ve included this code to make it an undirected, unweighted network for this exercise</span></span>
<span id="cb201-6"><a href="ch6.html#cb201-6" tabindex="-1"></a><span class="co"># for more information about network manipulation, see Chapter 5</span></span>
<span id="cb201-7"><a href="ch6.html#cb201-7" tabindex="-1"></a>UKfaculty <span class="ot">&lt;-</span> UKfaculty <span class="sc">|&gt;</span> <span class="fu">delete_edge_attr</span>(<span class="st">&quot;weight&quot;</span>) <span class="sc">|&gt;</span> <span class="fu">as.undirected</span>(<span class="at">mode =</span> <span class="st">&#39;mutual&#39;</span>)</span></code></pre></div>
<p>{TODO: Briefly describe the network.}</p>
<ol start="2" style="list-style-type: decimal">
<li>Answer the following questions:</li>
</ol>
<ul>
<li><p>How many nodes and edges does the network have?</p></li>
<li><p>How many network components does this network have? If it has more than one component, only retain the largest connected component before proceeding to the next part.</p></li>
<li><p>Compute the following macro-level network measures for this network:</p>
<ul>
<li>average degree</li>
<li>average shortest path length</li>
<li>global clustering coefficient</li>
<li>network density</li>
<li>network diameter</li>
<li>assortativity (by degree and by group) {footnote}</li>
<li>small world index</li>
</ul></li>
</ul>
<p>Footnote: <code>UKfaculty</code> contains a <code>Group</code> node attribute which denotes the department that each faculty member belonged to.</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="ch5.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="ch7.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/csqsiew/intro-to-igraph06-macro.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
